import 'dart:async';
import 'package:flutter/material.dart';

class GlobalVariables {
  //menu context
  static BuildContext? menuContext;
  static BuildContext? homescreenContext;
  //menu context

  //all item description
  static List allItemDescription = [];
  static List displayAllItemDescription = [];
  //all item description

  //customer service users
  static List customerServiceUsers = [];
  //customer service users

  //contacts
  static List contacts = [];
  //contacts

  //griview crossAxisCount
  static int axisCount = 2;
  //griview crossAxisCount

  //current devince info//
  static String deviceInfo = "";
  static String readdeviceInfo = "";
  static String appVersion = '';
  static String trigVarUPDTE = '';
  static String updteChangeLog = '';
  //current devince info//

  //menu
  static int menuCurrentIndex = 0;
  static bool menu0loaded = false;
  //menu

  //min order limit
  static double minOrderLimit = 0.0;
  //min order limit

  //static cut off time
  static String cutOffTime = '';
  //static cut off time

  //cart item count
  static int cartItemCount = 0;
  static List customerCart = [];
  static double cartTotalAmt = 0.0;
  static List customerCartToCheckout = [];
  static bool orderPlaced = false;
  static int chatCount = 0;
  //cart item count

  //order history
  static List orderHistory = [];
  static List orderDetails = [];
  static List orderAgainItems = [];
  //order history

  //timer
  static Timer? timerCartCount;
  static Timer? timerSessionInactivity;
  static Timer? timerCheckConcurrentLogIn;
  static Timer? timerChatCount;
  //timer

  //connection status
  static bool connected = false;
  //connection status

  //category list
  // for (var i = 0; i < 10; i++) {
  //   print(Color((math.Random().nextDouble() * 0xFFFFFF).toInt())
  //       .withOpacity(1.0));
  // }
  static List catColor = [
    Color(0xff29cf05),
    Color(0xffd04d23),
    Color(0xffcb2582),
    Color(0xff43a42d),
    Color(0xff293358),
    Color(0xff455e5c),
    Color(0xffab8cee),
    Color(0xffd6ebd0),
    Color(0xff1e916a),
    Color(0xff85d895),
    Color(0xff9aace5)
  ];
  static List category10 = [];
  static List category = [];
  static int selectedCategoryIndex = 0;
  static String selectedCategoryName = '';
  static String vendorcode = '';

  //category list

  //product list
  static List product50 = [];
  static List product = [];
  static List productDetails = [];
  static List searchProduct = [];
  static List productSimilar = [];
  static List productFavorites = [];
  //product list

  //customer success log
  static bool logcustomerFirstLogDone = false;
  static String logcustomerCode = '';
  static String logcustomerName = '';
  static String logcustomerAddress = '';
  static String logcustomerSM = '';
  static bool logcustomerApplyCreditLimit = false;
  static double logcustomerCreditLimit = 0.0;
  static double logcustomerCurrentCredit = 0.0;
  static int logcustomerAppRate = 0;
  //customer success log

  //forgot password
  static String forgotcustomerCode = '';
  static String forgotcustomerMobile = '';
  //forgot password

  //signup field holder
  static String ownerName = '';
  static String mobile = '';
  static String telephone = ' ';
  static String sitio = '';
  static String landmark = ' ';
  static String stown = '';
  static String stownCode = '';
  static String sbarangay = '';
  static String sbarangayCode = '';
  static String storeName = '';
  static String dti = ' ';
  static String holderStorePhotoPath = '';
  static String holderBCPhotoPath = '';
  //signup field holder

  //reply message holder
  static String isMsgActive = '';
  static String replyHolder = '';
  //reply message holder

  //payment method//
  static String selectedPaymentMethod = '';
  //payment method//

  //towns list//
  static List towns = [
    {
      "town_id": "1",
      "town_name": "Alburquerque",
      "prov_id": "1",
      "zipcode": "6302"
    },
    {"town_id": "2", "town_name": "Alicia", "prov_id": "1", "zipcode": "6314"},
    {"town_id": "3", "town_name": "Anda", "prov_id": "1", "zipcode": "6311"},
    {
      "town_id": "4",
      "town_name": "Antequera",
      "prov_id": "1",
      "zipcode": "6335"
    },
    {
      "town_id": "5",
      "town_name": "Baclayon",
      "prov_id": "1",
      "zipcode": "6301"
    },
    {
      "town_id": "6",
      "town_name": "Balilihan",
      "prov_id": "1",
      "zipcode": "6342"
    },
    {"town_id": "7", "town_name": "Batuan", "prov_id": "1", "zipcode": "6318"},
    {
      "town_id": "8",
      "town_name": "Bien Unido",
      "prov_id": "1",
      "zipcode": "6326"
    },
    {"town_id": "9", "town_name": "Bilar", "prov_id": "1", "zipcode": "6317"},
    {
      "town_id": "10",
      "town_name": "Buenavista",
      "prov_id": "1",
      "zipcode": "6333"
    },
    {"town_id": "11", "town_name": "Calape", "prov_id": "1", "zipcode": "6328"},
    {
      "town_id": "12",
      "town_name": "Candijay",
      "prov_id": "1",
      "zipcode": "6312"
    },
    {
      "town_id": "13",
      "town_name": "Carlos P. Garcia",
      "prov_id": "1",
      "zipcode": "6346"
    },
    {"town_id": "14", "town_name": "Carmen", "prov_id": "1", "zipcode": "6319"},
    {
      "town_id": "15",
      "town_name": "Catigbian",
      "prov_id": "1",
      "zipcode": "6343"
    },
    {"town_id": "16", "town_name": "Clarin", "prov_id": "1", "zipcode": "6330"},
    {
      "town_id": "17",
      "town_name": "Corella",
      "prov_id": "1",
      "zipcode": "6337"
    },
    {"town_id": "18", "town_name": "Cortes", "prov_id": "1", "zipcode": "6341"},
    {
      "town_id": "19",
      "town_name": "Dagohoy",
      "prov_id": "1",
      "zipcode": "6322"
    },
    {"town_id": "20", "town_name": "Danao", "prov_id": "1", "zipcode": "6344"},
    {"town_id": "21", "town_name": "Dauis", "prov_id": "1", "zipcode": "6339"},
    {"town_id": "22", "town_name": "Dimiao", "prov_id": "1", "zipcode": "6305"},
    {"town_id": "23", "town_name": "Duero", "prov_id": "1", "zipcode": "6309"},
    {
      "town_id": "24",
      "town_name": "Garcia Hernandez",
      "prov_id": "1",
      "zipcode": "6307"
    },
    {
      "town_id": "25",
      "town_name": "Guindulman",
      "prov_id": "1",
      "zipcode": "6310"
    },
    {
      "town_id": "26",
      "town_name": "Inabanga",
      "prov_id": "1",
      "zipcode": "6332"
    },
    {"town_id": "27", "town_name": "Jagna", "prov_id": "1", "zipcode": "6308"},
    {"town_id": "28", "town_name": "Getafe", "prov_id": "1", "zipcode": "6334"},
    {"town_id": "29", "town_name": "Lila", "prov_id": "1", "zipcode": "6304"},
    {"town_id": "30", "town_name": "Loay", "prov_id": "1", "zipcode": "6303"},
    {"town_id": "31", "town_name": "Loboc", "prov_id": "1", "zipcode": "6316"},
    {"town_id": "32", "town_name": "Loon", "prov_id": "1", "zipcode": "6327"},
    {"town_id": "33", "town_name": "Mabini", "prov_id": "1", "zipcode": "6313"},
    {
      "town_id": "34",
      "town_name": "Maribojoc",
      "prov_id": "1",
      "zipcode": "6336"
    },
    {
      "town_id": "35",
      "town_name": "Panglao",
      "prov_id": "1",
      "zipcode": "6340"
    },
    {"town_id": "36", "town_name": "Pilar", "prov_id": "1", "zipcode": "6321"},
    {
      "town_id": "37",
      "town_name": "Sagbayan",
      "prov_id": "1",
      "zipcode": "6331"
    },
    {
      "town_id": "38",
      "town_name": "San Isidro",
      "prov_id": "1",
      "zipcode": "6345"
    },
    {
      "town_id": "39",
      "town_name": "San Miguel",
      "prov_id": "1",
      "zipcode": "6323"
    },
    {
      "town_id": "40",
      "town_name": "Sevilla",
      "prov_id": "1",
      "zipcode": "6347"
    },
    {
      "town_id": "41",
      "town_name": "Sierra Bullones",
      "prov_id": "1",
      "zipcode": "6320"
    },
    {
      "town_id": "42",
      "town_name": "Sikatuna",
      "prov_id": "1",
      "zipcode": "6338"
    },
    {
      "town_id": "43",
      "town_name": "Tagbilaran City",
      "prov_id": "1",
      "zipcode": "6300"
    },
    {
      "town_id": "44",
      "town_name": "Talibon",
      "prov_id": "1",
      "zipcode": "6325"
    },
    {
      "town_id": "46",
      "town_name": "Trinidad",
      "prov_id": "1",
      "zipcode": "6324"
    },
    {
      "town_id": "47",
      "town_name": "Tubigon",
      "prov_id": "1",
      "zipcode": "6329"
    },
    {"town_id": "48", "town_name": "Ubay", "prov_id": "1", "zipcode": "6315"},
    {
      "town_id": "49",
      "town_name": "Valencia",
      "prov_id": "1",
      "zipcode": "6306"
    }
  ];
  //towns list//

  //barangay list//
  static List barangays = [
    {"brgy_id": "1", "town_id": "1", "brgy_name": "Bahi"},
    {"brgy_id": "2", "town_id": "1", "brgy_name": "Basacdacu"},
    {"brgy_id": "3", "town_id": "1", "brgy_name": "Cantinguib"},
    {"brgy_id": "4", "town_id": "1", "brgy_name": "Dangay"},
    {"brgy_id": "5", "town_id": "1", "brgy_name": "East Poblacion"},
    {"brgy_id": "6", "town_id": "1", "brgy_name": "Ponong"},
    {"brgy_id": "7", "town_id": "1", "brgy_name": "San Agustin"},
    {"brgy_id": "8", "town_id": "1", "brgy_name": "Santa Felomina"},
    {"brgy_id": "9", "town_id": "1", "brgy_name": "Tagbuane"},
    {"brgy_id": "10", "town_id": "1", "brgy_name": "Toril"},
    {"brgy_id": "11", "town_id": "1", "brgy_name": "West Poblacion"},
    {"brgy_id": "12", "town_id": "2", "brgy_name": "Cabatang"},
    {"brgy_id": "13", "town_id": "2", "brgy_name": "Cagongcagong"},
    {"brgy_id": "14", "town_id": "2", "brgy_name": "Cayacay"},
    {"brgy_id": "15", "town_id": "2", "brgy_name": "Del Monte"},
    {"brgy_id": "16", "town_id": "2", "brgy_name": "Katipunan"},
    {"brgy_id": "17", "town_id": "2", "brgy_name": "La Hacienda"},
    {"brgy_id": "18", "town_id": "2", "brgy_name": "Mahayag"},
    {"brgy_id": "19", "town_id": "2", "brgy_name": "Napo"},
    {"brgy_id": "20", "town_id": "2", "brgy_name": "Pagahat"},
    {"brgy_id": "21", "town_id": "2", "brgy_name": "Poblacion"},
    {"brgy_id": "22", "town_id": "3", "brgy_name": "Almaria"},
    {"brgy_id": "23", "town_id": "3", "brgy_name": "Bacong"},
    {"brgy_id": "24", "town_id": "3", "brgy_name": "Badiang"},
    {"brgy_id": "25", "town_id": "3", "brgy_name": "BuenaSuerte"},
    {"brgy_id": "26", "town_id": "3", "brgy_name": "Candabong"},
    {"brgy_id": "27", "town_id": "3", "brgy_name": "Casica"},
    {"brgy_id": "28", "town_id": "3", "brgy_name": "Katipunan"},
    {"brgy_id": "29", "town_id": "3", "brgy_name": "Linawan"},
    {"brgy_id": "30", "town_id": "3", "brgy_name": "Lundag"},
    {"brgy_id": "31", "town_id": "3", "brgy_name": "Poblacion"},
    {"brgy_id": "32", "town_id": "3", "brgy_name": "Suba"},
    {"brgy_id": "33", "town_id": "3", "brgy_name": "Talisay"},
    {"brgy_id": "34", "town_id": "3", "brgy_name": "Tanod"},
    {"brgy_id": "35", "town_id": "3", "brgy_name": "Tawid"},
    {"brgy_id": "36", "town_id": "3", "brgy_name": "Virgen"},
    {"brgy_id": "37", "town_id": "4", "brgy_name": "Angilan"},
    {"brgy_id": "38", "town_id": "4", "brgy_name": "Bantolinao"},
    {"brgy_id": "39", "town_id": "4", "brgy_name": "Bicahan"},
    {"brgy_id": "40", "town_id": "4", "brgy_name": "Bitaugan "},
    {"brgy_id": "41", "town_id": "4", "brgy_name": "Bungahan"},
    {"brgy_id": "42", "town_id": "4", "brgy_name": "Canlaas"},
    {"brgy_id": "43", "town_id": "4", "brgy_name": "Cansibuan"},
    {"brgy_id": "44", "town_id": "4", "brgy_name": "Can-omay"},
    {"brgy_id": "45", "town_id": "4", "brgy_name": "Celing"},
    {"brgy_id": "46", "town_id": "4", "brgy_name": "Danao "},
    {"brgy_id": "47", "town_id": "4", "brgy_name": "Danicop"},
    {"brgy_id": "48", "town_id": "4", "brgy_name": "Mag-aso"},
    {"brgy_id": "49", "town_id": "4", "brgy_name": "Poblacion"},
    {"brgy_id": "50", "town_id": "4", "brgy_name": "Quinapon-an"},
    {"brgy_id": "51", "town_id": "4", "brgy_name": "Santo Rosario "},
    {"brgy_id": "52", "town_id": "4", "brgy_name": "Tabuan"},
    {"brgy_id": "53", "town_id": "4", "brgy_name": "Tagubaas"},
    {"brgy_id": "54", "town_id": "4", "brgy_name": "Tupas"},
    {"brgy_id": "55", "town_id": "4", "brgy_name": "Obujan"},
    {"brgy_id": "56", "town_id": "4", "brgy_name": "Viga "},
    {"brgy_id": "57", "town_id": "4", "brgy_name": "Villa Aurora"},
    {"brgy_id": "58", "town_id": "5", "brgy_name": "Payahan"},
    {"brgy_id": "59", "town_id": "5", "brgy_name": "Cambanac"},
    {"brgy_id": "60", "town_id": "5", "brgy_name": "Dasitam"},
    {"brgy_id": "62", "town_id": "6", "brgy_name": "Hanopol Este"},
    {"brgy_id": "63", "town_id": "6", "brgy_name": "Hanopol Norte"},
    {"brgy_id": "64", "town_id": "5", "brgy_name": "Buenaventura"},
    {"brgy_id": "65", "town_id": "5", "brgy_name": "Guiwanon"},
    {"brgy_id": "66", "town_id": "5", "brgy_name": "Landican"},
    {"brgy_id": "67", "town_id": "5", "brgy_name": "Laya "},
    {"brgy_id": "68", "town_id": "5", "brgy_name": "Libertad"},
    {"brgy_id": "69", "town_id": "5", "brgy_name": "Montaña"},
    {"brgy_id": "70", "town_id": "5", "brgy_name": "Pamilacan"},
    {"brgy_id": "71", "town_id": "5", "brgy_name": "Poblacion"},
    {"brgy_id": "72", "town_id": "5", "brgy_name": "San Isidro "},
    {"brgy_id": "73", "town_id": "5", "brgy_name": "San Roque"},
    {"brgy_id": "74", "town_id": "5", "brgy_name": "San Vicente"},
    {"brgy_id": "75", "town_id": "5", "brgy_name": "Santa Cruz"},
    {"brgy_id": "76", "town_id": "5", "brgy_name": "Taguihon"},
    {"brgy_id": "77", "town_id": "5", "brgy_name": "Tanday "},
    {"brgy_id": "78", "town_id": "6", "brgy_name": "Baucan Norte"},
    {"brgy_id": "79", "town_id": "6", "brgy_name": "Baucan Sur"},
    {"brgy_id": "80", "town_id": "6", "brgy_name": "Boctol"},
    {"brgy_id": "81", "town_id": "6", "brgy_name": "Boyog Norte "},
    {"brgy_id": "82", "town_id": "6", "brgy_name": "Boyog Proper"},
    {"brgy_id": "83", "town_id": "6", "brgy_name": "Boyog Sur"},
    {"brgy_id": "84", "town_id": "6", "brgy_name": "Cabad"},
    {"brgy_id": "85", "town_id": "6", "brgy_name": "Candasig"},
    {"brgy_id": "86", "town_id": "6", "brgy_name": "Cantalid "},
    {"brgy_id": "87", "town_id": "6", "brgy_name": "Cantomimbo"},
    {"brgy_id": "88", "town_id": "6", "brgy_name": "Cogon"},
    {"brgy_id": "89", "town_id": "6", "brgy_name": "Datag Norte"},
    {"brgy_id": "90", "town_id": "6", "brgy_name": "Datag Sur"},
    {"brgy_id": "91", "town_id": "6", "brgy_name": "Del Carmen Este (Pob.) "},
    {"brgy_id": "92", "town_id": "6", "brgy_name": "Del Carmen Norte (Pob.)"},
    {"brgy_id": "93", "town_id": "6", "brgy_name": "Del Carmen Weste (Pob.)"},
    {"brgy_id": "94", "town_id": "6", "brgy_name": "Del Carmen Sur (Pob.)"},
    {"brgy_id": "95", "town_id": "6", "brgy_name": "Del Rosario"},
    {"brgy_id": "96", "town_id": "6", "brgy_name": "Dorol "},
    {"brgy_id": "97", "town_id": "6", "brgy_name": "Haguilan Grande"},
    {"brgy_id": "98", "town_id": "25", "brgy_name": "Cabantian"},
    {"brgy_id": "99", "town_id": "25", "brgy_name": "Canhaway"},
    {"brgy_id": "100", "town_id": "25", "brgy_name": "Guinacot"},
    {"brgy_id": "101", "town_id": "25", "brgy_name": "Sawang"},
    {"brgy_id": "102", "town_id": "25", "brgy_name": "Basdio"},
    {"brgy_id": "103", "town_id": "23", "brgy_name": "Itum"},
    {"brgy_id": "104", "town_id": "23", "brgy_name": "Guinsularan"},
    {"brgy_id": "105", "town_id": "25", "brgy_name": "Catungawan Norte"},
    {"brgy_id": "106", "town_id": "25", "brgy_name": "Mayuga"},
    {"brgy_id": "107", "town_id": "25", "brgy_name": "Bulawan"},
    {"brgy_id": "108", "town_id": "25", "brgy_name": "Biabas"},
    {"brgy_id": "109", "town_id": "49", "brgy_name": "Canmanico"},
    {"brgy_id": "110", "town_id": "49", "brgy_name": "Taytay"},
    {"brgy_id": "111", "town_id": "49", "brgy_name": "Poblacion Occidental"},
    {
      "brgy_id": "112",
      "town_id": "8",
      "brgy_name": "Bilangbilangan Dako      "
    },
    {"brgy_id": "113", "town_id": "8", "brgy_name": "Bilangbilangan Diot "},
    {"brgy_id": "114", "town_id": "8", "brgy_name": "Hingotanan East "},
    {"brgy_id": "115", "town_id": "8", "brgy_name": "Hingotanan West"},
    {"brgy_id": "120", "town_id": "8", "brgy_name": "Liberty"},
    {"brgy_id": "121", "town_id": "8", "brgy_name": "Malingin"},
    {"brgy_id": "122", "town_id": "8", "brgy_name": "Mandawa"},
    {"brgy_id": "123", "town_id": "8", "brgy_name": "Maomawan"},
    {"brgy_id": "124", "town_id": "8", "brgy_name": "Nueva Esperanza      "},
    {"brgy_id": "125", "town_id": "8", "brgy_name": "Nueva Estrella   "},
    {"brgy_id": "126", "town_id": "8", "brgy_name": "Pinamgo     "},
    {
      "brgy_id": "127",
      "town_id": "8",
      "brgy_name": "Poblacion (Bien Unido Proper"
    },
    {
      "brgy_id": "128",
      "town_id": "8",
      "brgy_name": "Puerto San Pedro (Lawis)  "
    },
    {"brgy_id": "129", "town_id": "8", "brgy_name": "Sagasa   "},
    {"brgy_id": "130", "town_id": "8", "brgy_name": "Tuboran"},
    {"brgy_id": "131", "town_id": "9", "brgy_name": "Bonifacio"},
    {"brgy_id": "132", "town_id": "9", "brgy_name": "Bugang Norte"},
    {"brgy_id": "133", "town_id": "9", "brgy_name": "Bugang Sur"},
    {"brgy_id": "134", "town_id": "9", "brgy_name": "Cabacnitan"},
    {"brgy_id": "135", "town_id": "9", "brgy_name": "Cambigsi"},
    {"brgy_id": "136", "town_id": "9", "brgy_name": "Campagao"},
    {"brgy_id": "137", "town_id": "9", "brgy_name": "Cansumbol"},
    {"brgy_id": "138", "town_id": "9", "brgy_name": "Dagohoy"},
    {"brgy_id": "139", "town_id": "9", "brgy_name": "Owac "},
    {"brgy_id": "140", "town_id": "9", "brgy_name": "Poblacion"},
    {"brgy_id": "141", "town_id": "9", "brgy_name": "Quezon"},
    {"brgy_id": "142", "town_id": "9", "brgy_name": "Riverside"},
    {"brgy_id": "143", "town_id": "9", "brgy_name": "Rizal"},
    {"brgy_id": "144", "town_id": "9", "brgy_name": "Roxas"},
    {"brgy_id": "145", "town_id": "9", "brgy_name": "Subayon"},
    {"brgy_id": "146", "town_id": "9", "brgy_name": "Villa Aurora"},
    {"brgy_id": "147", "town_id": "9", "brgy_name": "Villa Suerte"},
    {"brgy_id": "148", "town_id": "9", "brgy_name": "Yanaya"},
    {"brgy_id": "149", "town_id": "9", "brgy_name": "Zamora"},
    {"brgy_id": "150", "town_id": "10", "brgy_name": "Anonang"},
    {"brgy_id": "151", "town_id": "10", "brgy_name": "Asinan"},
    {"brgy_id": "152", "town_id": "10", "brgy_name": "Bago"},
    {"brgy_id": "153", "town_id": "10", "brgy_name": "Baluarte"},
    {"brgy_id": "154", "town_id": "10", "brgy_name": "Bantuan"},
    {"brgy_id": "155", "town_id": "10", "brgy_name": "Bato"},
    {"brgy_id": "156", "town_id": "10", "brgy_name": "Bonotbonot"},
    {"brgy_id": "157", "town_id": "10", "brgy_name": "Bugaong"},
    {"brgy_id": "158", "town_id": "10", "brgy_name": "Cambuhat"},
    {"brgy_id": "159", "town_id": "10", "brgy_name": "Cambus-oc"},
    {"brgy_id": "160", "town_id": "10", "brgy_name": "Cangawa"},
    {"brgy_id": "161", "town_id": "10", "brgy_name": "Cantomugcad"},
    {"brgy_id": "162", "town_id": "10", "brgy_name": "Cantores"},
    {"brgy_id": "163", "town_id": "10", "brgy_name": "Cantuba"},
    {"brgy_id": "164", "town_id": "10", "brgy_name": "Catigbian"},
    {"brgy_id": "165", "town_id": "10", "brgy_name": "Cawag"},
    {"brgy_id": "166", "town_id": "10", "brgy_name": "Cruz"},
    {"brgy_id": "167", "town_id": "10", "brgy_name": "Dait"},
    {"brgy_id": "168", "town_id": "10", "brgy_name": "Eastern Cabul-an"},
    {"brgy_id": "169", "town_id": "10", "brgy_name": "Hunan"},
    {"brgy_id": "170", "town_id": "10", "brgy_name": "Lapacan Norte"},
    {"brgy_id": "171", "town_id": "10", "brgy_name": "Lapacan Sur"},
    {"brgy_id": "172", "town_id": "10", "brgy_name": "Lubang"},
    {"brgy_id": "173", "town_id": "10", "brgy_name": "Lusong"},
    {"brgy_id": "174", "town_id": "10", "brgy_name": "Magkaya"},
    {"brgy_id": "175", "town_id": "10", "brgy_name": "Merryland"},
    {"brgy_id": "176", "town_id": "10", "brgy_name": "Nueva Granada"},
    {"brgy_id": "177", "town_id": "10", "brgy_name": "Nueva Montana"},
    {"brgy_id": "178", "town_id": "10", "brgy_name": "Overland"},
    {"brgy_id": "179", "town_id": "10", "brgy_name": "Panghagban"},
    {"brgy_id": "180", "town_id": "10", "brgy_name": "Poblacion"},
    {"brgy_id": "181", "town_id": "10", "brgy_name": "Puting Bato"},
    {"brgy_id": "182", "town_id": "10", "brgy_name": "Rufo Hill"},
    {"brgy_id": "183", "town_id": "10", "brgy_name": "Sweetland"},
    {"brgy_id": "184", "town_id": "10", "brgy_name": "Western Cabul-an"},
    {"brgy_id": "185", "town_id": "11", "brgy_name": "Abucayan Norte"},
    {"brgy_id": "186", "town_id": "11", "brgy_name": "Abucayan Sur"},
    {"brgy_id": "187", "town_id": "11", "brgy_name": "Banlasan"},
    {"brgy_id": "188", "town_id": "11", "brgy_name": "Bentig"},
    {"brgy_id": "189", "town_id": "11", "brgy_name": "Binogawan"},
    {"brgy_id": "190", "town_id": "11", "brgy_name": "Bonbon"},
    {"brgy_id": "191", "town_id": "11", "brgy_name": "Cabayugan"},
    {"brgy_id": "192", "town_id": "11", "brgy_name": "Cabudburan"},
    {"brgy_id": "193", "town_id": "11", "brgy_name": "Calunasan"},
    {"brgy_id": "194", "town_id": "11", "brgy_name": "Camias"},
    {"brgy_id": "195", "town_id": "11", "brgy_name": "Canguha"},
    {"brgy_id": "196", "town_id": "11", "brgy_name": "Catmonan"},
    {"brgy_id": "197", "town_id": "11", "brgy_name": "Desamparados"},
    {"brgy_id": "198", "town_id": "11", "brgy_name": "Kahayag"},
    {"brgy_id": "199", "town_id": "11", "brgy_name": "Kinabag-an"},
    {"brgy_id": "200", "town_id": "11", "brgy_name": "Labuon"},
    {"brgy_id": "201", "town_id": "11", "brgy_name": "Lawis"},
    {"brgy_id": "202", "town_id": "11", "brgy_name": "Liboron"},
    {"brgy_id": "203", "town_id": "11", "brgy_name": "Looc"},
    {"brgy_id": "204", "town_id": "11", "brgy_name": "Lomboy"},
    {"brgy_id": "205", "town_id": "11", "brgy_name": "Lucob"},
    {"brgy_id": "206", "town_id": "11", "brgy_name": "Madangog"},
    {"brgy_id": "207", "town_id": "11", "brgy_name": "Magtongtong"},
    {"brgy_id": "208", "town_id": "11", "brgy_name": "Mandaug"},
    {"brgy_id": "209", "town_id": "11", "brgy_name": "Mantatao"},
    {"brgy_id": "210", "town_id": "11", "brgy_name": "Sampoangon"},
    {"brgy_id": "211", "town_id": "11", "brgy_name": "San Isidro"},
    {"brgy_id": "212", "town_id": "11", "brgy_name": "Santa Cruz"},
    {"brgy_id": "213", "town_id": "11", "brgy_name": "Sohoton"},
    {"brgy_id": "214", "town_id": "11", "brgy_name": "Talisay"},
    {"brgy_id": "215", "town_id": "11", "brgy_name": "Tinibgan"},
    {"brgy_id": "216", "town_id": "11", "brgy_name": "Tultugan"},
    {"brgy_id": "217", "town_id": "11", "brgy_name": "Ulbujan"},
    {"brgy_id": "218", "town_id": "12", "brgy_name": "Abilihan"},
    {"brgy_id": "219", "town_id": "12", "brgy_name": "Anoling"},
    {"brgy_id": "220", "town_id": "12", "brgy_name": "Boyo-an"},
    {"brgy_id": "221", "town_id": "12", "brgy_name": "Cadapdapan"},
    {"brgy_id": "222", "town_id": "12", "brgy_name": "Cambane"},
    {"brgy_id": "223", "town_id": "12", "brgy_name": "Can-olin"},
    {"brgy_id": "224", "town_id": "12", "brgy_name": "Canawa"},
    {"brgy_id": "225", "town_id": "12", "brgy_name": "Cogtong"},
    {"brgy_id": "226", "town_id": "12", "brgy_name": "La Union"},
    {"brgy_id": "227", "town_id": "12", "brgy_name": "Luan"},
    {"brgy_id": "228", "town_id": "12", "brgy_name": "Lungsoda-an"},
    {"brgy_id": "229", "town_id": "12", "brgy_name": "Mahangin"},
    {"brgy_id": "230", "town_id": "12", "brgy_name": "Pagahat"},
    {"brgy_id": "231", "town_id": "12", "brgy_name": "Panadtaran"},
    {"brgy_id": "232", "town_id": "12", "brgy_name": "Panas"},
    {"brgy_id": "233", "town_id": "12", "brgy_name": "Poblacion"},
    {"brgy_id": "234", "town_id": "12", "brgy_name": "San Isidro"},
    {"brgy_id": "235", "town_id": "12", "brgy_name": "Tambongan"},
    {"brgy_id": "236", "town_id": "12", "brgy_name": "Tawid"},
    {"brgy_id": "237", "town_id": "12", "brgy_name": "Tugas"},
    {"brgy_id": "238", "town_id": "12", "brgy_name": "Tubod"},
    {"brgy_id": "239", "town_id": "13", "brgy_name": "Aguining"},
    {"brgy_id": "240", "town_id": "13", "brgy_name": "Basiao"},
    {"brgy_id": "241", "town_id": "13", "brgy_name": "Baud"},
    {"brgy_id": "242", "town_id": "13", "brgy_name": "Bayog"},
    {"brgy_id": "243", "town_id": "13", "brgy_name": "Bogo"},
    {"brgy_id": "244", "town_id": "13", "brgy_name": "Bonbonon"},
    {"brgy_id": "245", "town_id": "13", "brgy_name": "Canmangao"},
    {"brgy_id": "246", "town_id": "13", "brgy_name": "Campamanog"},
    {"brgy_id": "247", "town_id": "13", "brgy_name": "Gaus"},
    {"brgy_id": "248", "town_id": "13", "brgy_name": "Kabangkalan"},
    {"brgy_id": "249", "town_id": "13", "brgy_name": "Lapinig"},
    {"brgy_id": "250", "town_id": "13", "brgy_name": "Lipata"},
    {"brgy_id": "251", "town_id": "13", "brgy_name": "Poblacion"},
    {"brgy_id": "252", "town_id": "13", "brgy_name": "Popoo"},
    {"brgy_id": "253", "town_id": "13", "brgy_name": "Saguise"},
    {"brgy_id": "254", "town_id": "13", "brgy_name": "San Jose"},
    {"brgy_id": "255", "town_id": "13", "brgy_name": "Santo Rosario"},
    {"brgy_id": "256", "town_id": "13", "brgy_name": "Tilmobo"},
    {"brgy_id": "257", "town_id": "13", "brgy_name": "Tugnao"},
    {"brgy_id": "258", "town_id": "13", "brgy_name": "Villa Milagrosa"},
    {"brgy_id": "259", "town_id": "13", "brgy_name": "Butan"},
    {"brgy_id": "260", "town_id": "13", "brgy_name": "San Vicente"},
    {"brgy_id": "261", "town_id": "14", "brgy_name": "Alegria"},
    {"brgy_id": "262", "town_id": "14", "brgy_name": "Bicao"},
    {"brgy_id": "263", "town_id": "14", "brgy_name": "Buenavista"},
    {"brgy_id": "264", "town_id": "14", "brgy_name": "Buenos Aires"},
    {"brgy_id": "265", "town_id": "14", "brgy_name": "Calatrava"},
    {"brgy_id": "266", "town_id": "14", "brgy_name": "El Progreso"},
    {"brgy_id": "267", "town_id": "14", "brgy_name": "El Salvador"},
    {"brgy_id": "268", "town_id": "14", "brgy_name": "Guadalupe"},
    {"brgy_id": "269", "town_id": "14", "brgy_name": "Katipunan"},
    {"brgy_id": "270", "town_id": "14", "brgy_name": "La Liberted"},
    {"brgy_id": "271", "town_id": "14", "brgy_name": "La Paz"},
    {"brgy_id": "272", "town_id": "14", "brgy_name": "La Salvacion"},
    {"brgy_id": "273", "town_id": "14", "brgy_name": "La Victoria"},
    {"brgy_id": "274", "town_id": "14", "brgy_name": "Matin-ao"},
    {"brgy_id": "275", "town_id": "14", "brgy_name": "Montehermoso"},
    {"brgy_id": "276", "town_id": "14", "brgy_name": "MonteSuerte"},
    {"brgy_id": "277", "town_id": "14", "brgy_name": "Montesunting"},
    {"brgy_id": "278", "town_id": "14", "brgy_name": "Montevideo"},
    {"brgy_id": "279", "town_id": "14", "brgy_name": "Nueva Fuerza"},
    {"brgy_id": "280", "town_id": "14", "brgy_name": "Nueva Vida Este"},
    {"brgy_id": "281", "town_id": "14", "brgy_name": "Nueva Vida Sur"},
    {"brgy_id": "282", "town_id": "14", "brgy_name": "Nueva Vida Norte"},
    {"brgy_id": "283", "town_id": "14", "brgy_name": "Poblacion Norte"},
    {"brgy_id": "284", "town_id": "14", "brgy_name": "Poblacion Sur"},
    {"brgy_id": "285", "town_id": "14", "brgy_name": "Tambo-an"},
    {"brgy_id": "286", "town_id": "14", "brgy_name": "Vallehermoso"},
    {"brgy_id": "287", "town_id": "14", "brgy_name": "Villaflor"},
    {"brgy_id": "288", "town_id": "14", "brgy_name": "Villafuerte"},
    {"brgy_id": "289", "town_id": "14", "brgy_name": "Villacayo"},
    {"brgy_id": "290", "town_id": "15", "brgy_name": "Alegria"},
    {"brgy_id": "291", "town_id": "15", "brgy_name": "Ambuan"},
    {"brgy_id": "292", "town_id": "15", "brgy_name": "Baang"},
    {"brgy_id": "293", "town_id": "15", "brgy_name": "Bagtic"},
    {"brgy_id": "294", "town_id": "15", "brgy_name": "Bonbong"},
    {"brgy_id": "295", "town_id": "15", "brgy_name": "Cambailan"},
    {"brgy_id": "296", "town_id": "15", "brgy_name": "Candumayao"},
    {"brgy_id": "297", "town_id": "15", "brgy_name": "Kang-iras"},
    {"brgy_id": "298", "town_id": "15", "brgy_name": "Causwagan Norte"},
    {"brgy_id": "299", "town_id": "15", "brgy_name": "Hagbuaya"},
    {"brgy_id": "300", "town_id": "15", "brgy_name": "Haguilanan"},
    {"brgy_id": "301", "town_id": "15", "brgy_name": "Libertad Sur"},
    {"brgy_id": "302", "town_id": "15", "brgy_name": "Liboron"},
    {"brgy_id": "303", "town_id": "15", "brgy_name": "Mahayag Norte"},
    {"brgy_id": "304", "town_id": "15", "brgy_name": "Mahayag Sur"},
    {"brgy_id": "305", "town_id": "15", "brgy_name": "Maitum"},
    {"brgy_id": "306", "town_id": "15", "brgy_name": "Mantasida"},
    {"brgy_id": "307", "town_id": "15", "brgy_name": "Poblacion"},
    {"brgy_id": "308", "town_id": "15", "brgy_name": "Poblacion Weste"},
    {"brgy_id": "309", "town_id": "15", "brgy_name": "Rizal"},
    {"brgy_id": "310", "town_id": "15", "brgy_name": "Sinakayanan"},
    {"brgy_id": "311", "town_id": "15", "brgy_name": "Triple Union"},
    {"brgy_id": "312", "town_id": "16", "brgy_name": "Bacani"},
    {"brgy_id": "313", "town_id": "16", "brgy_name": "Bogtongbod"},
    {"brgy_id": "314", "town_id": "16", "brgy_name": "Bonbon"},
    {"brgy_id": "315", "town_id": "16", "brgy_name": "Bontud"},
    {"brgy_id": "316", "town_id": "16", "brgy_name": "Buacao"},
    {"brgy_id": "317", "town_id": "16", "brgy_name": "Buangan"},
    {"brgy_id": "318", "town_id": "16", "brgy_name": "Cabog"},
    {"brgy_id": "319", "town_id": "16", "brgy_name": "Caboy"},
    {"brgy_id": "320", "town_id": "16", "brgy_name": "Caluwasan"},
    {"brgy_id": "321", "town_id": "16", "brgy_name": "Candajec"},
    {"brgy_id": "322", "town_id": "16", "brgy_name": "Cantoyoc"},
    {"brgy_id": "323", "town_id": "16", "brgy_name": "Comaang"},
    {"brgy_id": "324", "town_id": "16", "brgy_name": "Danahao"},
    {"brgy_id": "325", "town_id": "16", "brgy_name": "Katipunan"},
    {"brgy_id": "326", "town_id": "16", "brgy_name": "Lajog"},
    {"brgy_id": "327", "town_id": "16", "brgy_name": "Mataub"},
    {"brgy_id": "328", "town_id": "16", "brgy_name": "Nahawan"},
    {"brgy_id": "329", "town_id": "16", "brgy_name": "Poblacion Centro"},
    {"brgy_id": "330", "town_id": "16", "brgy_name": "Poblacion Norte"},
    {"brgy_id": "331", "town_id": "16", "brgy_name": "Poblacion Sur"},
    {"brgy_id": "332", "town_id": "16", "brgy_name": "Tangaran"},
    {"brgy_id": "333", "town_id": "16", "brgy_name": "Tontunan"},
    {"brgy_id": "334", "town_id": "16", "brgy_name": "Tubod"},
    {"brgy_id": "335", "town_id": "16", "brgy_name": "Villaflor"},
    {"brgy_id": "336", "town_id": "35", "brgy_name": "Libaong"},
    {"brgy_id": "337", "town_id": "35", "brgy_name": "Tawala"},
    {"brgy_id": "338", "town_id": "35", "brgy_name": "Danao"},
    {"brgy_id": "339", "town_id": "35", "brgy_name": "Doljo"},
    {"brgy_id": "340", "town_id": "35", "brgy_name": "Tangnan"},
    {"brgy_id": "341", "town_id": "35", "brgy_name": "Poblacion"},
    {"brgy_id": "342", "town_id": "35", "brgy_name": "Looc"},
    {"brgy_id": "343", "town_id": "35", "brgy_name": "Bolod"},
    {"brgy_id": "344", "town_id": "35", "brgy_name": "Bil-isan"},
    {"brgy_id": "345", "town_id": "2", "brgy_name": "Progreso"},
    {"brgy_id": "346", "town_id": "2", "brgy_name": "Putlongcam"},
    {"brgy_id": "347", "town_id": "2", "brgy_name": "Sudlon"},
    {"brgy_id": "348", "town_id": "2", "brgy_name": "Untaga"},
    {"brgy_id": "349", "town_id": "2", "brgy_name": "Cambaol"},
    {"brgy_id": "350", "town_id": "3", "brgy_name": "Santa Cruz"},
    {"brgy_id": "351", "town_id": "6", "brgy_name": "Hanopol Weste"},
    {"brgy_id": "352", "town_id": "6", "brgy_name": "Magsija"},
    {"brgy_id": "353", "town_id": "6", "brgy_name": "Maslog"},
    {"brgy_id": "354", "town_id": "6", "brgy_name": "Sagasa"},
    {"brgy_id": "355", "town_id": "6", "brgy_name": "Sal-ing"},
    {"brgy_id": "356", "town_id": "6", "brgy_name": "San Isidro"},
    {"brgy_id": "357", "town_id": "6", "brgy_name": "San Roque"},
    {"brgy_id": "358", "town_id": "6", "brgy_name": "Santo Niño"},
    {"brgy_id": "359", "town_id": "6", "brgy_name": "Tagustusan"},
    {"brgy_id": "360", "town_id": "4", "brgy_name": "Ubojan"},
    {"brgy_id": "361", "town_id": "7", "brgy_name": "Aloja"},
    {
      "brgy_id": "362",
      "town_id": "7",
      "brgy_name": "Behind the Clouds (San Jose)"
    },
    {"brgy_id": "363", "town_id": "7", "brgy_name": "Cabacnitan"},
    {"brgy_id": "364", "town_id": "7", "brgy_name": "Cambacay"},
    {"brgy_id": "365", "town_id": "7", "brgy_name": "Cantigdas"},
    {"brgy_id": "366", "town_id": "7", "brgy_name": "Garcia"},
    {"brgy_id": "367", "town_id": "7", "brgy_name": "Janlud"},
    {"brgy_id": "368", "town_id": "7", "brgy_name": "Poblacion Norte"},
    {"brgy_id": "369", "town_id": "7", "brgy_name": "Poblacion Sur"},
    {
      "brgy_id": "370",
      "town_id": "7",
      "brgy_name": "Poblacion Vieja (Longsudaan)"
    },
    {"brgy_id": "371", "town_id": "7", "brgy_name": "Quezon"},
    {"brgy_id": "372", "town_id": "7", "brgy_name": "Quirino"},
    {"brgy_id": "373", "town_id": "7", "brgy_name": "Rizal"},
    {"brgy_id": "374", "town_id": "7", "brgy_name": "Rosariohan"},
    {"brgy_id": "375", "town_id": "7", "brgy_name": "Santa Cruz"},
    {"brgy_id": "376", "town_id": "13", "brgy_name": "Tugas"},
    {"brgy_id": "377", "town_id": "17", "brgy_name": "Anislag"},
    {"brgy_id": "378", "town_id": "17", "brgy_name": "Canangca-an "},
    {"brgy_id": "379", "town_id": "17", "brgy_name": "Canapnapan"},
    {"brgy_id": "380", "town_id": "17", "brgy_name": "Cancatac"},
    {"brgy_id": "381", "town_id": "17", "brgy_name": "Pandol"},
    {"brgy_id": "382", "town_id": "17", "brgy_name": "Poblacion"},
    {"brgy_id": "383", "town_id": "17", "brgy_name": "Sambog"},
    {"brgy_id": "384", "town_id": "17", "brgy_name": "Tanday"},
    {"brgy_id": "385", "town_id": "18", "brgy_name": "De la Paz"},
    {"brgy_id": "386", "town_id": "18", "brgy_name": "Fatima"},
    {"brgy_id": "387", "town_id": "18", "brgy_name": "Loreto"},
    {"brgy_id": "388", "town_id": "18", "brgy_name": "Lourdes"},
    {"brgy_id": "389", "town_id": "18", "brgy_name": "Malayo Norte"},
    {"brgy_id": "390", "town_id": "18", "brgy_name": "Malayo Sur"},
    {"brgy_id": "391", "town_id": "18", "brgy_name": "Montserrat"},
    {"brgy_id": "392", "town_id": "18", "brgy_name": "New Lourdes"},
    {"brgy_id": "393", "town_id": "18", "brgy_name": "Patrocinio"},
    {"brgy_id": "394", "town_id": "18", "brgy_name": "Poblacion"},
    {"brgy_id": "395", "town_id": "18", "brgy_name": "Rosario"},
    {"brgy_id": "396", "town_id": "18", "brgy_name": "Salvador"},
    {"brgy_id": "397", "town_id": "18", "brgy_name": "San Roque"},
    {"brgy_id": "398", "town_id": "18", "brgy_name": "Upper de la Paz"},
    {"brgy_id": "399", "town_id": "19", "brgy_name": "Babag"},
    {"brgy_id": "400", "town_id": "19", "brgy_name": "Cagawasan"},
    {"brgy_id": "401", "town_id": "19", "brgy_name": "Cagawitan"},
    {"brgy_id": "402", "town_id": "19", "brgy_name": "Caluasan"},
    {"brgy_id": "403", "town_id": "19", "brgy_name": "Can-oling"},
    {"brgy_id": "404", "town_id": "19", "brgy_name": "Candelaria"},
    {"brgy_id": "405", "town_id": "19", "brgy_name": "Estaca"},
    {"brgy_id": "406", "town_id": "19", "brgy_name": "La Esperanza"},
    {"brgy_id": "407", "town_id": "19", "brgy_name": "Mahayag"},
    {"brgy_id": "408", "town_id": "19", "brgy_name": "Malitbog"},
    {"brgy_id": "409", "town_id": "19", "brgy_name": "Poblacion"},
    {"brgy_id": "410", "town_id": "19", "brgy_name": "San Miguel"},
    {"brgy_id": "411", "town_id": "19", "brgy_name": "San Vicente"},
    {"brgy_id": "412", "town_id": "19", "brgy_name": "Santa Cruz"},
    {"brgy_id": "413", "town_id": "19", "brgy_name": "Villa Aurora"},
    {"brgy_id": "414", "town_id": "20", "brgy_name": "Cabatuan"},
    {"brgy_id": "415", "town_id": "20", "brgy_name": "Cantubod"},
    {"brgy_id": "416", "town_id": "20", "brgy_name": "Carbon"},
    {"brgy_id": "417", "town_id": "20", "brgy_name": "Concepcion"},
    {"brgy_id": "418", "town_id": "20", "brgy_name": "Dagohoy"},
    {"brgy_id": "419", "town_id": "20", "brgy_name": "Hibale"},
    {"brgy_id": "420", "town_id": "20", "brgy_name": "Magtangtang"},
    {"brgy_id": "421", "town_id": "20", "brgy_name": "Nahud"},
    {"brgy_id": "422", "town_id": "20", "brgy_name": "Poblacion"},
    {"brgy_id": "423", "town_id": "20", "brgy_name": "Remedios"},
    {"brgy_id": "424", "town_id": "20", "brgy_name": "San Carlos"},
    {"brgy_id": "425", "town_id": "20", "brgy_name": "San Miguel"},
    {"brgy_id": "426", "town_id": "20", "brgy_name": "Santa Fe"},
    {"brgy_id": "427", "town_id": "20", "brgy_name": "Santo Niño"},
    {"brgy_id": "428", "town_id": "20", "brgy_name": "Tabok"},
    {"brgy_id": "429", "town_id": "20", "brgy_name": "Taming"},
    {"brgy_id": "430", "town_id": "20", "brgy_name": "Villa Anunciado"},
    {"brgy_id": "431", "town_id": "21", "brgy_name": "Biking"},
    {"brgy_id": "432", "town_id": "21", "brgy_name": "Bingag"},
    {"brgy_id": "433", "town_id": "21", "brgy_name": "Catarman"},
    {"brgy_id": "434", "town_id": "21", "brgy_name": "Dao"},
    {"brgy_id": "435", "town_id": "21", "brgy_name": "Mariveles"},
    {"brgy_id": "436", "town_id": "21", "brgy_name": "Mayacabac"},
    {"brgy_id": "437", "town_id": "21", "brgy_name": "Poblacion"},
    {"brgy_id": "438", "town_id": "21", "brgy_name": "San Isidro"},
    {"brgy_id": "439", "town_id": "21", "brgy_name": "Songculan"},
    {"brgy_id": "440", "town_id": "21", "brgy_name": "Tabalong"},
    {"brgy_id": "441", "town_id": "21", "brgy_name": "Tinago"},
    {"brgy_id": "442", "town_id": "21", "brgy_name": "Totolan"},
    {"brgy_id": "443", "town_id": "22", "brgy_name": "Abihid"},
    {"brgy_id": "444", "town_id": "22", "brgy_name": "Alemania"},
    {"brgy_id": "445", "town_id": "22", "brgy_name": "Baguhan"},
    {"brgy_id": "446", "town_id": "22", "brgy_name": "Bakilid"},
    {"brgy_id": "447", "town_id": "22", "brgy_name": "Balbalan"},
    {"brgy_id": "448", "town_id": "22", "brgy_name": "Banban"},
    {"brgy_id": "449", "town_id": "22", "brgy_name": "Bauhugan"},
    {"brgy_id": "450", "town_id": "22", "brgy_name": "Bilisan"},
    {"brgy_id": "451", "town_id": "22", "brgy_name": "Cabagakian"},
    {"brgy_id": "452", "town_id": "22", "brgy_name": "Cabanbanan"},
    {"brgy_id": "453", "town_id": "22", "brgy_name": "Cadap-agan"},
    {"brgy_id": "454", "town_id": "22", "brgy_name": "Cambacol"},
    {"brgy_id": "455", "town_id": "22", "brgy_name": "Cambayaon"},
    {"brgy_id": "456", "town_id": "22", "brgy_name": "Canhayupon"},
    {"brgy_id": "457", "town_id": "22", "brgy_name": "Canlambong"},
    {"brgy_id": "458", "town_id": "22", "brgy_name": "Casingan"},
    {"brgy_id": "459", "town_id": "22", "brgy_name": "Catugasan"},
    {"brgy_id": "460", "town_id": "22", "brgy_name": "Datag"},
    {"brgy_id": "461", "town_id": "22", "brgy_name": "Guindaguitan"},
    {"brgy_id": "462", "town_id": "22", "brgy_name": "Guingoyuran"},
    {"brgy_id": "463", "town_id": "22", "brgy_name": "Ile"},
    {"brgy_id": "464", "town_id": "22", "brgy_name": "Lapsaon"},
    {"brgy_id": "465", "town_id": "22", "brgy_name": "Limokon Ilaod"},
    {"brgy_id": "466", "town_id": "22", "brgy_name": "Limokon Ilaya"},
    {"brgy_id": "467", "town_id": "22", "brgy_name": "Luyo"},
    {"brgy_id": "468", "town_id": "22", "brgy_name": "Malijao"},
    {"brgy_id": "469", "town_id": "22", "brgy_name": "Oac"},
    {"brgy_id": "470", "town_id": "22", "brgy_name": "Pagsa"},
    {"brgy_id": "471", "town_id": "22", "brgy_name": "Pangihawan"},
    {"brgy_id": "472", "town_id": "22", "brgy_name": "Puangyuta"},
    {"brgy_id": "473", "town_id": "22", "brgy_name": "Sawang"},
    {"brgy_id": "474", "town_id": "22", "brgy_name": "Tangohay"},
    {"brgy_id": "475", "town_id": "22", "brgy_name": "Taongon Cabatuan"},
    {"brgy_id": "476", "town_id": "22", "brgy_name": "Taongon Can-andam"},
    {"brgy_id": "477", "town_id": "22", "brgy_name": "Tawid Bitaog"},
    {"brgy_id": "478", "town_id": "23", "brgy_name": "Alejawan"},
    {"brgy_id": "479", "town_id": "23", "brgy_name": "Angilan"},
    {"brgy_id": "480", "town_id": "23", "brgy_name": "Anibongan"},
    {"brgy_id": "481", "town_id": "23", "brgy_name": "Bangwalog"},
    {"brgy_id": "482", "town_id": "23", "brgy_name": "Cansuhay"},
    {"brgy_id": "483", "town_id": "23", "brgy_name": "Danao"},
    {"brgy_id": "484", "town_id": "23", "brgy_name": "Duay"},
    {"brgy_id": "485", "town_id": "23", "brgy_name": "Imelda"},
    {"brgy_id": "486", "town_id": "23", "brgy_name": "Langkis"},
    {"brgy_id": "487", "town_id": "23", "brgy_name": "Lobogon"},
    {"brgy_id": "488", "town_id": "23", "brgy_name": "Madua Norte"},
    {"brgy_id": "489", "town_id": "23", "brgy_name": "Madua Sur"},
    {"brgy_id": "490", "town_id": "23", "brgy_name": "Mambool"},
    {"brgy_id": "491", "town_id": "23", "brgy_name": "Mawi"},
    {"brgy_id": "492", "town_id": "23", "brgy_name": "Payao"},
    {"brgy_id": "493", "town_id": "23", "brgy_name": "San Antonio"},
    {"brgy_id": "494", "town_id": "23", "brgy_name": "San Isidro"},
    {"brgy_id": "495", "town_id": "23", "brgy_name": "San Pedro"},
    {"brgy_id": "496", "town_id": "23", "brgy_name": "Taytay"},
    {"brgy_id": "497", "town_id": "24", "brgy_name": "Abijilan"},
    {"brgy_id": "498", "town_id": "24", "brgy_name": "Antipolo"},
    {"brgy_id": "499", "town_id": "24", "brgy_name": "Basiao"},
    {"brgy_id": "500", "town_id": "24", "brgy_name": "Cagwang"},
    {"brgy_id": "501", "town_id": "24", "brgy_name": "Calma"},
    {"brgy_id": "502", "town_id": "24", "brgy_name": "Cambuyo"},
    {"brgy_id": "503", "town_id": "24", "brgy_name": "Canayaon East"},
    {"brgy_id": "504", "town_id": "24", "brgy_name": "Canayaon West"},
    {"brgy_id": "505", "town_id": "24", "brgy_name": "Candanas"},
    {"brgy_id": "506", "town_id": "24", "brgy_name": "Candulao"},
    {"brgy_id": "507", "town_id": "24", "brgy_name": "Catmon"},
    {"brgy_id": "508", "town_id": "24", "brgy_name": "Cayam"},
    {"brgy_id": "509", "town_id": "24", "brgy_name": "Cupa"},
    {"brgy_id": "510", "town_id": "24", "brgy_name": "Datag"},
    {"brgy_id": "511", "town_id": "24", "brgy_name": "Estaca"},
    {"brgy_id": "512", "town_id": "24", "brgy_name": "Libertad"},
    {"brgy_id": "513", "town_id": "24", "brgy_name": "Lungsodaan East"},
    {"brgy_id": "514", "town_id": "24", "brgy_name": "Lungsodaan West"},
    {"brgy_id": "515", "town_id": "24", "brgy_name": "Malinao"},
    {"brgy_id": "516", "town_id": "24", "brgy_name": "Manaba"},
    {"brgy_id": "517", "town_id": "24", "brgy_name": "Pasong"},
    {"brgy_id": "518", "town_id": "24", "brgy_name": "Poblacion East"},
    {"brgy_id": "519", "town_id": "24", "brgy_name": "Poblacion West"},
    {"brgy_id": "520", "town_id": "24", "brgy_name": "Sacaon"},
    {"brgy_id": "521", "town_id": "24", "brgy_name": "Sampong"},
    {"brgy_id": "522", "town_id": "24", "brgy_name": "Tabuan"},
    {"brgy_id": "523", "town_id": "24", "brgy_name": "Togbongon"},
    {"brgy_id": "524", "town_id": "24", "brgy_name": "Ulbujan East"},
    {"brgy_id": "525", "town_id": "24", "brgy_name": "Ulbujan West"},
    {"brgy_id": "526", "town_id": "24", "brgy_name": "Victoria"},
    {"brgy_id": "527", "town_id": "25", "brgy_name": "Bato"},
    {"brgy_id": "528", "town_id": "25", "brgy_name": "Bayong"},
    {"brgy_id": "529", "town_id": "25", "brgy_name": "Casbu"},
    {"brgy_id": "530", "town_id": "25", "brgy_name": "Catungawan Sur"},
    {"brgy_id": "531", "town_id": "25", "brgy_name": "Guio-ang"},
    {"brgy_id": "532", "town_id": "25", "brgy_name": "Lombog"},
    {"brgy_id": "533", "town_id": "25", "brgy_name": "Tabajan"},
    {"brgy_id": "534", "town_id": "25", "brgy_name": "Tabunok"},
    {"brgy_id": "535", "town_id": "25", "brgy_name": "Trinidad"},
    {"brgy_id": "536", "town_id": "25", "brgy_name": "Cansiwang"},
    {"brgy_id": "537", "town_id": "26", "brgy_name": "Anonang"},
    {"brgy_id": "538", "town_id": "26", "brgy_name": "Bahan"},
    {"brgy_id": "539", "town_id": "26", "brgy_name": "Badiang"},
    {"brgy_id": "540", "town_id": "26", "brgy_name": "Baguhan"},
    {"brgy_id": "541", "town_id": "26", "brgy_name": "Banahao"},
    {"brgy_id": "542", "town_id": "26", "brgy_name": "Baogo"},
    {"brgy_id": "543", "town_id": "26", "brgy_name": "Bugang"},
    {"brgy_id": "544", "town_id": "26", "brgy_name": "Cagawasan"},
    {"brgy_id": "545", "town_id": "26", "brgy_name": "Cagayan"},
    {"brgy_id": "546", "town_id": "26", "brgy_name": "Cambitoon"},
    {"brgy_id": "547", "town_id": "26", "brgy_name": "Canlinte"},
    {"brgy_id": "548", "town_id": "26", "brgy_name": "Cawayan"},
    {"brgy_id": "549", "town_id": "26", "brgy_name": "Cogon"},
    {"brgy_id": "550", "town_id": "26", "brgy_name": "Cuaming"},
    {"brgy_id": "551", "town_id": "26", "brgy_name": "Dagnawan"},
    {"brgy_id": "552", "town_id": "26", "brgy_name": "Dagohoy"},
    {"brgy_id": "553", "town_id": "26", "brgy_name": "Dait Sur"},
    {"brgy_id": "554", "town_id": "26", "brgy_name": "Datag"},
    {"brgy_id": "555", "town_id": "26", "brgy_name": "Fatima"},
    {"brgy_id": "556", "town_id": "26", "brgy_name": "Hambongan"},
    {"brgy_id": "557", "town_id": "26", "brgy_name": "Ilaud"},
    {"brgy_id": "558", "town_id": "26", "brgy_name": "Ilaya"},
    {"brgy_id": "559", "town_id": "26", "brgy_name": "Ilihan"},
    {"brgy_id": "560", "town_id": "26", "brgy_name": "Lapacan Norte"},
    {"brgy_id": "561", "town_id": "26", "brgy_name": "Lapacan Sur"},
    {"brgy_id": "562", "town_id": "26", "brgy_name": "Lawis"},
    {"brgy_id": "563", "town_id": "26", "brgy_name": "Liloan Norte"},
    {"brgy_id": "564", "town_id": "26", "brgy_name": "Liloan Sur"},
    {"brgy_id": "565", "town_id": "26", "brgy_name": "Lomboy"},
    {"brgy_id": "566", "town_id": "26", "brgy_name": "Lonoy Cainsican"},
    {"brgy_id": "567", "town_id": "26", "brgy_name": "Lonoy Roma"},
    {"brgy_id": "568", "town_id": "26", "brgy_name": "Lutao"},
    {"brgy_id": "569", "town_id": "26", "brgy_name": "Luyo"},
    {"brgy_id": "570", "town_id": "26", "brgy_name": "Mabuhay"},
    {"brgy_id": "571", "town_id": "26", "brgy_name": "Maria Rosario"},
    {"brgy_id": "572", "town_id": "26", "brgy_name": "Nabuad"},
    {"brgy_id": "573", "town_id": "26", "brgy_name": "Napo"},
    {"brgy_id": "574", "town_id": "26", "brgy_name": "Ondol"},
    {"brgy_id": "575", "town_id": "26", "brgy_name": "Poblacion"},
    {"brgy_id": "576", "town_id": "26", "brgy_name": "Riverside"},
    {"brgy_id": "577", "town_id": "26", "brgy_name": "Saa"},
    {"brgy_id": "578", "town_id": "26", "brgy_name": "San Isidro"},
    {"brgy_id": "579", "town_id": "26", "brgy_name": "San Jose"},
    {"brgy_id": "580", "town_id": "26", "brgy_name": "Santo Niño"},
    {"brgy_id": "581", "town_id": "26", "brgy_name": "Santo Rosario"},
    {"brgy_id": "582", "town_id": "26", "brgy_name": "Sua"},
    {"brgy_id": "583", "town_id": "26", "brgy_name": "Tambook"},
    {"brgy_id": "584", "town_id": "26", "brgy_name": "Tungod"},
    {"brgy_id": "585", "town_id": "26", "brgy_name": "U-og"},
    {"brgy_id": "586", "town_id": "26", "brgy_name": "Ubujan"},
    {"brgy_id": "587", "town_id": "27", "brgy_name": "Alejawan"},
    {"brgy_id": "588", "town_id": "27", "brgy_name": "Balili"},
    {"brgy_id": "589", "town_id": "27", "brgy_name": "Boctol"},
    {"brgy_id": "590", "town_id": "27", "brgy_name": "Bunga Ilaya"},
    {"brgy_id": "591", "town_id": "27", "brgy_name": "Bunga Mar"},
    {"brgy_id": "592", "town_id": "27", "brgy_name": "Buyog"},
    {"brgy_id": "593", "town_id": "27", "brgy_name": "Cabunga-an"},
    {"brgy_id": "594", "town_id": "27", "brgy_name": "Calabacita"},
    {"brgy_id": "595", "town_id": "27", "brgy_name": "Cambugason"},
    {"brgy_id": "596", "town_id": "27", "brgy_name": "Can-ipol"},
    {"brgy_id": "597", "town_id": "27", "brgy_name": "Can-uba"},
    {"brgy_id": "598", "town_id": "27", "brgy_name": "Can-upao"},
    {"brgy_id": "599", "town_id": "27", "brgy_name": "Canjulao"},
    {"brgy_id": "600", "town_id": "27", "brgy_name": "Cantagay"},
    {"brgy_id": "601", "town_id": "27", "brgy_name": "Cantuyoc"},
    {"brgy_id": "602", "town_id": "27", "brgy_name": "Faraon"},
    {"brgy_id": "603", "town_id": "27", "brgy_name": "Ipil"},
    {"brgy_id": "604", "town_id": "27", "brgy_name": "Kinagbaan"},
    {"brgy_id": "605", "town_id": "27", "brgy_name": "Laca"},
    {"brgy_id": "606", "town_id": "27", "brgy_name": "Larapan"},
    {"brgy_id": "607", "town_id": "27", "brgy_name": "Lonoy"},
    {"brgy_id": "608", "town_id": "27", "brgy_name": "Looc"},
    {"brgy_id": "609", "town_id": "27", "brgy_name": "Malbog"},
    {"brgy_id": "610", "town_id": "27", "brgy_name": "Mayana"},
    {"brgy_id": "611", "town_id": "27", "brgy_name": "Naatang"},
    {"brgy_id": "612", "town_id": "27", "brgy_name": "Nausok"},
    {"brgy_id": "613", "town_id": "27", "brgy_name": "Odiong"},
    {"brgy_id": "614", "town_id": "27", "brgy_name": "Pagina"},
    {"brgy_id": "615", "town_id": "27", "brgy_name": "Pangdan"},
    {"brgy_id": "616", "town_id": "27", "brgy_name": "Poblacion"},
    {"brgy_id": "617", "town_id": "27", "brgy_name": "Tejero"},
    {"brgy_id": "618", "town_id": "27", "brgy_name": "Tubod Mar"},
    {"brgy_id": "619", "town_id": "27", "brgy_name": "Tubod Monte"},
    {"brgy_id": "620", "town_id": "28", "brgy_name": "Alumar"},
    {"brgy_id": "621", "town_id": "28", "brgy_name": "Banacon"},
    {"brgy_id": "622", "town_id": "28", "brgy_name": "Buyog"},
    {"brgy_id": "623", "town_id": "28", "brgy_name": "Cabasakan"},
    {"brgy_id": "624", "town_id": "28", "brgy_name": "Campao Occidental"},
    {"brgy_id": "625", "town_id": "28", "brgy_name": "Campao Oriental"},
    {"brgy_id": "626", "town_id": "28", "brgy_name": "Cangmundo"},
    {"brgy_id": "627", "town_id": "28", "brgy_name": "Carlos P. Garcia"},
    {"brgy_id": "628", "town_id": "28", "brgy_name": "Corte Baud"},
    {"brgy_id": "629", "town_id": "28", "brgy_name": "Handumon"},
    {"brgy_id": "630", "town_id": "28", "brgy_name": "Jagoliao"},
    {"brgy_id": "631", "town_id": "28", "brgy_name": "Jandayan Norte"},
    {"brgy_id": "632", "town_id": "28", "brgy_name": "Jandayan Sur"},
    {"brgy_id": "633", "town_id": "28", "brgy_name": "Mahanay"},
    {"brgy_id": "634", "town_id": "28", "brgy_name": "Nasingin"},
    {"brgy_id": "635", "town_id": "28", "brgy_name": "Pandanon"},
    {"brgy_id": "636", "town_id": "28", "brgy_name": "Poblacion"},
    {"brgy_id": "637", "town_id": "28", "brgy_name": "Saguise"},
    {"brgy_id": "638", "town_id": "28", "brgy_name": "Salog"},
    {"brgy_id": "639", "town_id": "28", "brgy_name": "San Jose"},
    {"brgy_id": "640", "town_id": "28", "brgy_name": "Santo Niño"},
    {"brgy_id": "641", "town_id": "28", "brgy_name": "Taytay"},
    {"brgy_id": "642", "town_id": "28", "brgy_name": "Tugas"},
    {"brgy_id": "643", "town_id": "28", "brgy_name": "Tulang"},
    {"brgy_id": "644", "town_id": "29", "brgy_name": "Banban"},
    {"brgy_id": "645", "town_id": "29", "brgy_name": "Bonkokan Ilaya"},
    {"brgy_id": "646", "town_id": "29", "brgy_name": "Bonkokan Ubos"},
    {"brgy_id": "647", "town_id": "29", "brgy_name": "Calvario"},
    {"brgy_id": "648", "town_id": "29", "brgy_name": "Candulang"},
    {"brgy_id": "649", "town_id": "29", "brgy_name": "Catugasan"},
    {"brgy_id": "650", "town_id": "29", "brgy_name": "Cayupo"},
    {"brgy_id": "651", "town_id": "29", "brgy_name": "Cogon"},
    {"brgy_id": "652", "town_id": "29", "brgy_name": "Jambawan"},
    {"brgy_id": "653", "town_id": "29", "brgy_name": "La Fortuna"},
    {"brgy_id": "654", "town_id": "29", "brgy_name": "Lomanoy"},
    {"brgy_id": "655", "town_id": "29", "brgy_name": "Macalingan"},
    {"brgy_id": "657", "town_id": "29", "brgy_name": "Malinao East"},
    {"brgy_id": "658", "town_id": "29", "brgy_name": "Malinao West"},
    {"brgy_id": "659", "town_id": "29", "brgy_name": "Nagsulay"},
    {"brgy_id": "660", "town_id": "29", "brgy_name": "Poblacion"},
    {"brgy_id": "661", "town_id": "29", "brgy_name": "Taug"},
    {"brgy_id": "662", "town_id": "29", "brgy_name": "Tiguis"},
    {"brgy_id": "663", "town_id": "30", "brgy_name": "Agape"},
    {"brgy_id": "664", "town_id": "30", "brgy_name": "Alegria Norte"},
    {"brgy_id": "665", "town_id": "30", "brgy_name": "Alegria Sur"},
    {"brgy_id": "666", "town_id": "30", "brgy_name": "Bonbon"},
    {"brgy_id": "667", "town_id": "30", "brgy_name": "Botoc Occidental"},
    {"brgy_id": "668", "town_id": "30", "brgy_name": "Botoc Oriental"},
    {"brgy_id": "669", "town_id": "30", "brgy_name": "Calvario"},
    {"brgy_id": "670", "town_id": "30", "brgy_name": "Concepcion"},
    {"brgy_id": "671", "town_id": "30", "brgy_name": "Hinawanan"},
    {"brgy_id": "672", "town_id": "30", "brgy_name": "Las Salinas Norte"},
    {"brgy_id": "673", "town_id": "30", "brgy_name": "Las Salinas Sur"},
    {"brgy_id": "674", "town_id": "30", "brgy_name": "Palo"},
    {"brgy_id": "675", "town_id": "30", "brgy_name": "Poblacion Ibabao"},
    {"brgy_id": "676", "town_id": "30", "brgy_name": "Poblacion Ubos"},
    {"brgy_id": "677", "town_id": "30", "brgy_name": "Sagnap"},
    {"brgy_id": "678", "town_id": "30", "brgy_name": "Tambangan"},
    {"brgy_id": "679", "town_id": "30", "brgy_name": "Tangcasan Norte"},
    {"brgy_id": "680", "town_id": "30", "brgy_name": "Tangcasan Sur"},
    {"brgy_id": "681", "town_id": "30", "brgy_name": "Tayong Occidental"},
    {"brgy_id": "682", "town_id": "30", "brgy_name": "Tayong Oriental"},
    {"brgy_id": "683", "town_id": "30", "brgy_name": "Tocdog Dacu"},
    {"brgy_id": "684", "town_id": "30", "brgy_name": "Tocdog Ilaya"},
    {"brgy_id": "685", "town_id": "30", "brgy_name": "Villalimpia"},
    {"brgy_id": "686", "town_id": "30", "brgy_name": "Yanangan"},
    {"brgy_id": "687", "town_id": "31", "brgy_name": "Agape"},
    {"brgy_id": "688", "town_id": "31", "brgy_name": "Canlasid"},
    {"brgy_id": "689", "town_id": "31", "brgy_name": "Gon-ob"},
    {"brgy_id": "690", "town_id": "31", "brgy_name": "Gotozon"},
    {"brgy_id": "691", "town_id": "31", "brgy_name": "Jimilian"},
    {"brgy_id": "692", "town_id": "31", "brgy_name": "Oy"},
    {"brgy_id": "693", "town_id": "31", "brgy_name": "Poblacion Ondol"},
    {"brgy_id": "694", "town_id": "31", "brgy_name": "Poblacion Sawang"},
    {"brgy_id": "695", "town_id": "31", "brgy_name": "Quinoguitan"},
    {"brgy_id": "696", "town_id": "31", "brgy_name": "Taytay"},
    {"brgy_id": "697", "town_id": "31", "brgy_name": "Tigbao"},
    {"brgy_id": "698", "town_id": "31", "brgy_name": "Ugpong"},
    {"brgy_id": "699", "town_id": "31", "brgy_name": "Candasag"},
    {"brgy_id": "700", "town_id": "31", "brgy_name": "Candabong"},
    {"brgy_id": "701", "town_id": "31", "brgy_name": "Cambance"},
    {"brgy_id": "702", "town_id": "31", "brgy_name": "Alegria"},
    {"brgy_id": "703", "town_id": "31", "brgy_name": "Bagumbayan"},
    {"brgy_id": "704", "town_id": "31", "brgy_name": "Bahian"},
    {"brgy_id": "705", "town_id": "31", "brgy_name": "Bonbon Lower"},
    {"brgy_id": "706", "town_id": "31", "brgy_name": "Bonbon Upper"},
    {"brgy_id": "707", "town_id": "31", "brgy_name": "Buenavista"},
    {"brgy_id": "708", "town_id": "31", "brgy_name": "Bugho"},
    {"brgy_id": "709", "town_id": "31", "brgy_name": "Cabadiangan"},
    {"brgy_id": "710", "town_id": "31", "brgy_name": "Calunasan Norte"},
    {"brgy_id": "711", "town_id": "31", "brgy_name": "Calunasan Sur"},
    {"brgy_id": "712", "town_id": "31", "brgy_name": "Camayaan"},
    {"brgy_id": "713", "town_id": "31", "brgy_name": "Villadolid"},
    {"brgy_id": "714", "town_id": "31", "brgy_name": "Villaflor"},
    {"brgy_id": "715", "town_id": "32", "brgy_name": "Moto Norte"},
    {"brgy_id": "716", "town_id": "32", "brgy_name": "Mocpoc Sur"},
    {"brgy_id": "717", "town_id": "32", "brgy_name": "Mocpoc Norte"},
    {"brgy_id": "718", "town_id": "32", "brgy_name": "Looc"},
    {"brgy_id": "719", "town_id": "32", "brgy_name": "Lintuan"},
    {"brgy_id": "720", "town_id": "32", "brgy_name": "Genomoan"},
    {"brgy_id": "721", "town_id": "32", "brgy_name": "Cogon Sur"},
    {"brgy_id": "722", "town_id": "32", "brgy_name": "Cuasi"},
    {"brgy_id": "723", "town_id": "32", "brgy_name": "Cogon Norte"},
    {"brgy_id": "724", "town_id": "32", "brgy_name": "Catagbacan Sur"},
    {"brgy_id": "725", "town_id": "32", "brgy_name": "Catagbacan Norte"},
    {"brgy_id": "726", "town_id": "32", "brgy_name": "Catagbacan Handig"},
    {"brgy_id": "727", "town_id": "32", "brgy_name": "Cantumocad"},
    {"brgy_id": "728", "town_id": "32", "brgy_name": "Moto Sur"},
    {"brgy_id": "729", "town_id": "32", "brgy_name": "Nagtuang"},
    {"brgy_id": "730", "town_id": "32", "brgy_name": "Pondol"},
    {"brgy_id": "731", "town_id": "32", "brgy_name": "Pig-ot"},
    {"brgy_id": "732", "town_id": "32", "brgy_name": "Pantudlan"},
    {"brgy_id": "733", "town_id": "32", "brgy_name": "Panangquilon"},
    {"brgy_id": "734", "town_id": "32", "brgy_name": "Nueva Vida"},
    {"brgy_id": "735", "town_id": "32", "brgy_name": "Napo"},
    {"brgy_id": "736", "town_id": "32", "brgy_name": "Cantaongon"},
    {"brgy_id": "737", "town_id": "32", "brgy_name": "Ticugan"},
    {"brgy_id": "738", "town_id": "32", "brgy_name": "Quinobcoban"},
    {"brgy_id": "739", "town_id": "32", "brgy_name": "Taytay"},
    {"brgy_id": "740", "town_id": "32", "brgy_name": "Tangnan"},
    {"brgy_id": "741", "town_id": "32", "brgy_name": "Tan-awan"},
    {"brgy_id": "742", "town_id": "32", "brgy_name": "Talisay"},
    {"brgy_id": "743", "town_id": "32", "brgy_name": "Song-on"},
    {"brgy_id": "744", "town_id": "32", "brgy_name": "Sondol"},
    {"brgy_id": "745", "town_id": "32", "brgy_name": "Cantam-is Baslay"},
    {"brgy_id": "746", "town_id": "32", "brgy_name": "Cabacongan"},
    {"brgy_id": "747", "town_id": "32", "brgy_name": "Bugho"},
    {"brgy_id": "748", "town_id": "32", "brgy_name": "Bongco"},
    {"brgy_id": "749", "town_id": "32", "brgy_name": "Biasong"},
    {"brgy_id": "750", "town_id": "32", "brgy_name": "Basdio"},
    {"brgy_id": "751", "town_id": "32", "brgy_name": "Basdacu"},
    {"brgy_id": "752", "town_id": "32", "brgy_name": "Basac"},
    {"brgy_id": "753", "town_id": "32", "brgy_name": "Bahi"},
    {"brgy_id": "754", "town_id": "32", "brgy_name": "Bagacay Saong"},
    {"brgy_id": "755", "town_id": "32", "brgy_name": "Bagacay Kawayan"},
    {"brgy_id": "756", "town_id": "32", "brgy_name": "Bagacay Katipuhan"},
    {"brgy_id": "757", "town_id": "32", "brgy_name": "Badbad Oriental"},
    {"brgy_id": "758", "town_id": "32", "brgy_name": "Badbad Occidental"},
    {"brgy_id": "759", "town_id": "32", "brgy_name": "Cabadug"},
    {"brgy_id": "760", "town_id": "32", "brgy_name": "Cabug"},
    {"brgy_id": "761", "town_id": "32", "brgy_name": "Cantam-is Bago"},
    {"brgy_id": "762", "town_id": "32", "brgy_name": "Cansubayon"},
    {"brgy_id": "763", "town_id": "32", "brgy_name": "Cansuagwit"},
    {"brgy_id": "764", "town_id": "32", "brgy_name": "Canmanoc"},
    {"brgy_id": "765", "town_id": "32", "brgy_name": "Canmaag"},
    {"brgy_id": "766", "town_id": "32", "brgy_name": "Canigaan"},
    {"brgy_id": "767", "town_id": "32", "brgy_name": "Canhangdon Oriental"},
    {"brgy_id": "768", "town_id": "32", "brgy_name": "Canhangdon Occidental"},
    {"brgy_id": "769", "town_id": "32", "brgy_name": "Candaigan"},
    {"brgy_id": "770", "town_id": "32", "brgy_name": "Campatud"},
    {"brgy_id": "771", "town_id": "32", "brgy_name": "Cambaquiz"},
    {"brgy_id": "772", "town_id": "32", "brgy_name": "Calayugan Sur"},
    {"brgy_id": "773", "town_id": "32", "brgy_name": "Calayugan Norte"},
    {"brgy_id": "774", "town_id": "32", "brgy_name": "Agsoso"},
    {"brgy_id": "775", "town_id": "32", "brgy_name": "Tiwi"},
    {"brgy_id": "776", "town_id": "32", "brgy_name": "Tontonan"},
    {"brgy_id": "777", "town_id": "32", "brgy_name": "Tubodacu"},
    {"brgy_id": "778", "town_id": "32", "brgy_name": "Tubodio"},
    {"brgy_id": "779", "town_id": "32", "brgy_name": "Tubuan"},
    {"brgy_id": "780", "town_id": "32", "brgy_name": "Ubayon"},
    {"brgy_id": "781", "town_id": "32", "brgy_name": "Ubojan"},
    {"brgy_id": "782", "town_id": "33", "brgy_name": "Abaca"},
    {"brgy_id": "783", "town_id": "33", "brgy_name": "Paraiso"},
    {"brgy_id": "784", "town_id": "33", "brgy_name": "Poblacion I"},
    {"brgy_id": "785", "town_id": "33", "brgy_name": "Poblacion II"},
    {"brgy_id": "786", "town_id": "33", "brgy_name": "San Isidro"},
    {"brgy_id": "787", "town_id": "33", "brgy_name": "San Jose"},
    {"brgy_id": "788", "town_id": "33", "brgy_name": "San Rafael"},
    {"brgy_id": "789", "town_id": "33", "brgy_name": "San Roque"},
    {"brgy_id": "790", "town_id": "33", "brgy_name": "Tambo"},
    {"brgy_id": "791", "town_id": "33", "brgy_name": "Tangkigan"},
    {"brgy_id": "792", "town_id": "33", "brgy_name": "Minol"},
    {"brgy_id": "793", "town_id": "33", "brgy_name": "Marcelo"},
    {"brgy_id": "794", "town_id": "33", "brgy_name": "Abad Santos"},
    {"brgy_id": "795", "town_id": "33", "brgy_name": "Aguipo"},
    {"brgy_id": "796", "town_id": "33", "brgy_name": "Baybayon"},
    {"brgy_id": "797", "town_id": "33", "brgy_name": "Bulawan"},
    {"brgy_id": "798", "town_id": "33", "brgy_name": "Cabidian"},
    {"brgy_id": "799", "town_id": "33", "brgy_name": "Cawayanan"},
    {"brgy_id": "800", "town_id": "33", "brgy_name": "Concepcion"},
    {"brgy_id": "801", "town_id": "33", "brgy_name": "Del Mar"},
    {"brgy_id": "802", "town_id": "33", "brgy_name": "Lungsoda-an"},
    {"brgy_id": "803", "town_id": "33", "brgy_name": "Valaga"},
    {"brgy_id": "804", "town_id": "34", "brgy_name": "Agahay"},
    {"brgy_id": "805", "town_id": "34", "brgy_name": "Lincod"},
    {"brgy_id": "806", "town_id": "34", "brgy_name": "Pagnitoan"},
    {"brgy_id": "807", "town_id": "34", "brgy_name": "Poblacion"},
    {"brgy_id": "808", "town_id": "34", "brgy_name": "Punsod"},
    {"brgy_id": "809", "town_id": "34", "brgy_name": "Punta Cruz"},
    {"brgy_id": "810", "town_id": "34", "brgy_name": "San Isidro"},
    {"brgy_id": "811", "town_id": "34", "brgy_name": "San Roque"},
    {"brgy_id": "812", "town_id": "34", "brgy_name": "San Vicente"},
    {"brgy_id": "813", "town_id": "34", "brgy_name": "Tinibgan"},
    {"brgy_id": "814", "town_id": "34", "brgy_name": "Lagtangon"},
    {"brgy_id": "815", "town_id": "34", "brgy_name": "Jandig"},
    {"brgy_id": "816", "town_id": "34", "brgy_name": "Aliguay"},
    {"brgy_id": "817", "town_id": "34", "brgy_name": "Anislag"},
    {"brgy_id": "818", "town_id": "34", "brgy_name": "Bayacabac"},
    {"brgy_id": "819", "town_id": "34", "brgy_name": "Bood"},
    {"brgy_id": "820", "town_id": "34", "brgy_name": "Busao"},
    {"brgy_id": "821", "town_id": "34", "brgy_name": "Cabawan"},
    {"brgy_id": "822", "town_id": "34", "brgy_name": "Candavid"},
    {"brgy_id": "823", "town_id": "34", "brgy_name": "Dipatlong"},
    {"brgy_id": "824", "town_id": "34", "brgy_name": "Guiwanon"},
    {"brgy_id": "825", "town_id": "34", "brgy_name": "Toril"},
    {"brgy_id": "826", "town_id": "35", "brgy_name": "Lourdes"},
    {"brgy_id": "827", "town_id": "36", "brgy_name": "Aurora"},
    {"brgy_id": "828", "town_id": "36", "brgy_name": "La Suerte"},
    {"brgy_id": "829", "town_id": "36", "brgy_name": "Lumbay"},
    {"brgy_id": "830", "town_id": "36", "brgy_name": "Lundag"},
    {"brgy_id": "831", "town_id": "36", "brgy_name": "Pamacsalan"},
    {"brgy_id": "832", "town_id": "36", "brgy_name": "Poblacion"},
    {"brgy_id": "833", "town_id": "36", "brgy_name": "Rizal"},
    {"brgy_id": "834", "town_id": "36", "brgy_name": "San Carlos"},
    {"brgy_id": "835", "town_id": "36", "brgy_name": "San Isidro"},
    {"brgy_id": "836", "town_id": "36", "brgy_name": "Inaghuban"},
    {"brgy_id": "837", "town_id": "36", "brgy_name": "Ilaud"},
    {"brgy_id": "838", "town_id": "36", "brgy_name": "Estaca"},
    {"brgy_id": "839", "town_id": "36", "brgy_name": "Bagacay"},
    {"brgy_id": "840", "town_id": "36", "brgy_name": "Bagumbayan"},
    {"brgy_id": "841", "town_id": "36", "brgy_name": "Bayong"},
    {"brgy_id": "842", "town_id": "36", "brgy_name": "Buenasuerte"},
    {"brgy_id": "843", "town_id": "36", "brgy_name": "Cagawasan"},
    {"brgy_id": "844", "town_id": "36", "brgy_name": "Cansungay"},
    {"brgy_id": "845", "town_id": "36", "brgy_name": "Catagdaan"},
    {"brgy_id": "846", "town_id": "36", "brgy_name": "Del Pilar"},
    {"brgy_id": "847", "town_id": "36", "brgy_name": "San Vicente"},
    {"brgy_id": "848", "town_id": "37", "brgy_name": "Calangahan"},
    {"brgy_id": "849", "town_id": "37", "brgy_name": "Sagbayan Sur"},
    {"brgy_id": "850", "town_id": "37", "brgy_name": "San Agustin"},
    {"brgy_id": "851", "town_id": "37", "brgy_name": "San Antonio"},
    {"brgy_id": "852", "town_id": "37", "brgy_name": "San Isidro"},
    {"brgy_id": "853", "town_id": "37", "brgy_name": "San Ramon"},
    {"brgy_id": "854", "town_id": "37", "brgy_name": "San Roque"},
    {"brgy_id": "855", "town_id": "37", "brgy_name": "San Vicente Norte"},
    {"brgy_id": "856", "town_id": "37", "brgy_name": "San Vicente Sur\t"},
    {"brgy_id": "857", "town_id": "37", "brgy_name": "Santa Catalina"},
    {"brgy_id": "858", "town_id": "37", "brgy_name": "Santa Cruz"},
    {"brgy_id": "859", "town_id": "37", "brgy_name": "Poblacion"},
    {"brgy_id": "860", "town_id": "37", "brgy_name": "Mantalongon"},
    {"brgy_id": "861", "town_id": "37", "brgy_name": "Canmano"},
    {"brgy_id": "862", "town_id": "37", "brgy_name": "Canmaya Centro"},
    {"brgy_id": "863", "town_id": "37", "brgy_name": "Canmaya Diot"},
    {"brgy_id": "864", "town_id": "37", "brgy_name": "Dagnawan"},
    {"brgy_id": "865", "town_id": "37", "brgy_name": "Kabasacan"},
    {"brgy_id": "866", "town_id": "37", "brgy_name": "Kagawasan"},
    {"brgy_id": "867", "town_id": "37", "brgy_name": "Katipunan"},
    {"brgy_id": "868", "town_id": "37", "brgy_name": "Langtad"},
    {"brgy_id": "869", "town_id": "37", "brgy_name": "Libertad Norte"},
    {"brgy_id": "870", "town_id": "37", "brgy_name": "Libertad Sur"},
    {"brgy_id": "871", "town_id": "37", "brgy_name": "Ubojan"},
    {"brgy_id": "872", "town_id": "38", "brgy_name": "Abehilan"},
    {"brgy_id": "873", "town_id": "38", "brgy_name": "Cansague Sur"},
    {"brgy_id": "874", "town_id": "38", "brgy_name": "Cansague Norte"},
    {"brgy_id": "875", "town_id": "38", "brgy_name": "Candungao"},
    {"brgy_id": "876", "town_id": "38", "brgy_name": "Cambansag"},
    {"brgy_id": "877", "town_id": "38", "brgy_name": "Caimbang"},
    {"brgy_id": "878", "town_id": "38", "brgy_name": "Cabanugan"},
    {"brgy_id": "879", "town_id": "38", "brgy_name": "Baunos"},
    {"brgy_id": "880", "town_id": "38", "brgy_name": "Baryong Daan"},
    {"brgy_id": "881", "town_id": "38", "brgy_name": "Causwagan Sur"},
    {"brgy_id": "882", "town_id": "38", "brgy_name": "Masonoy"},
    {"brgy_id": "883", "town_id": "38", "brgy_name": "Poblacion"},
    {"brgy_id": "884", "town_id": "39", "brgy_name": "Bayongan"},
    {"brgy_id": "885", "town_id": "39", "brgy_name": "Bugang"},
    {"brgy_id": "886", "town_id": "39", "brgy_name": "Santo Niño"},
    {"brgy_id": "887", "town_id": "39", "brgy_name": "San Vicente"},
    {"brgy_id": "888", "town_id": "39", "brgy_name": "San Jose"},
    {"brgy_id": "889", "town_id": "39", "brgy_name": "San Isidro"},
    {"brgy_id": "890", "town_id": "39", "brgy_name": "Poblacion"},
    {"brgy_id": "891", "town_id": "39", "brgy_name": "Mahayag"},
    {"brgy_id": "892", "town_id": "39", "brgy_name": "Kagawasan"},
    {"brgy_id": "893", "town_id": "39", "brgy_name": "Hagbuyo"},
    {"brgy_id": "894", "town_id": "39", "brgy_name": "Garcia"},
    {"brgy_id": "895", "town_id": "39", "brgy_name": "Corazon"},
    {"brgy_id": "896", "town_id": "39", "brgy_name": "Capayas"},
    {"brgy_id": "897", "town_id": "39", "brgy_name": "Cambangay Norte"},
    {"brgy_id": "898", "town_id": "39", "brgy_name": "Camanaga"},
    {"brgy_id": "899", "town_id": "39", "brgy_name": "Caluasan"},
    {"brgy_id": "900", "town_id": "39", "brgy_name": "Cabangahan"},
    {"brgy_id": "901", "town_id": "39", "brgy_name": "Tomoc"},
    {"brgy_id": "902", "town_id": "40", "brgy_name": "Bayawahan"},
    {"brgy_id": "903", "town_id": "40", "brgy_name": "Magsaysay"},
    {"brgy_id": "904", "town_id": "40", "brgy_name": "Lobgob"},
    {"brgy_id": "905", "town_id": "40", "brgy_name": "Licolico"},
    {"brgy_id": "906", "town_id": "40", "brgy_name": "Lagtangan"},
    {"brgy_id": "907", "town_id": "40", "brgy_name": "Guinob-an"},
    {"brgy_id": "908", "town_id": "40", "brgy_name": "Ewon"},
    {"brgy_id": "909", "town_id": "40", "brgy_name": "Cambagui"},
    {"brgy_id": "910", "town_id": "40", "brgy_name": "Calinginan Sur"},
    {"brgy_id": "911", "town_id": "40", "brgy_name": "Calinginan Norte"},
    {"brgy_id": "912", "town_id": "40", "brgy_name": "Calinga-an"},
    {"brgy_id": "913", "town_id": "40", "brgy_name": "Cabancalan"},
    {"brgy_id": "914", "town_id": "40", "brgy_name": "Poblacion"},
    {"brgy_id": "915", "town_id": "41", "brgy_name": "Abachanan"},
    {"brgy_id": "916", "town_id": "41", "brgy_name": "Matin-ao"},
    {"brgy_id": "917", "town_id": "41", "brgy_name": "Nan-od"},
    {"brgy_id": "918", "town_id": "41", "brgy_name": "Poblacion"},
    {"brgy_id": "919", "town_id": "41", "brgy_name": "Salvador"},
    {"brgy_id": "920", "town_id": "41", "brgy_name": "San Agustin"},
    {"brgy_id": "921", "town_id": "41", "brgy_name": "San Isidro"},
    {"brgy_id": "922", "town_id": "41", "brgy_name": "San Jose"},
    {"brgy_id": "923", "town_id": "41", "brgy_name": "San Juan"},
    {"brgy_id": "924", "town_id": "41", "brgy_name": "Santa Cruz"},
    {"brgy_id": "925", "town_id": "41", "brgy_name": "Magsaysay"},
    {"brgy_id": "926", "town_id": "41", "brgy_name": "Lataban"},
    {"brgy_id": "927", "town_id": "41", "brgy_name": "Anibongan"},
    {"brgy_id": "928", "town_id": "41", "brgy_name": "Bugsoc"},
    {"brgy_id": "929", "town_id": "41", "brgy_name": "Cahayag"},
    {"brgy_id": "930", "town_id": "41", "brgy_name": "Canlangit"},
    {"brgy_id": "931", "town_id": "41", "brgy_name": "Canta-ub"},
    {"brgy_id": "932", "town_id": "41", "brgy_name": "Casilay"},
    {"brgy_id": "933", "town_id": "41", "brgy_name": "Danicop"},
    {"brgy_id": "934", "town_id": "41", "brgy_name": "Dusita"},
    {"brgy_id": "935", "town_id": "41", "brgy_name": "La Union"},
    {"brgy_id": "936", "town_id": "41", "brgy_name": "Villa Garcia"},
    {"brgy_id": "937", "town_id": "42", "brgy_name": "Abucay Norte"},
    {"brgy_id": "938", "town_id": "42", "brgy_name": "Poblacion I"},
    {"brgy_id": "939", "town_id": "42", "brgy_name": "Libjo"},
    {"brgy_id": "940", "town_id": "42", "brgy_name": "Canagong"},
    {"brgy_id": "941", "town_id": "42", "brgy_name": "Cambuac Sur"},
    {"brgy_id": "942", "town_id": "42", "brgy_name": "Cambuac Norte"},
    {"brgy_id": "943", "town_id": "42", "brgy_name": "Bahaybahay"},
    {"brgy_id": "944", "town_id": "42", "brgy_name": "Badiang"},
    {"brgy_id": "945", "town_id": "42", "brgy_name": "Abucay Sur"},
    {"brgy_id": "946", "town_id": "42", "brgy_name": "Poblacion II"},
    {"brgy_id": "947", "town_id": "44", "brgy_name": "Bagacay"},
    {"brgy_id": "948", "town_id": "44", "brgy_name": "San Carlos"},
    {"brgy_id": "949", "town_id": "44", "brgy_name": "San Francisco"},
    {"brgy_id": "950", "town_id": "44", "brgy_name": "San Isidro"},
    {"brgy_id": "951", "town_id": "44", "brgy_name": "San Jose"},
    {"brgy_id": "952", "town_id": "44", "brgy_name": "San Pedro"},
    {"brgy_id": "953", "town_id": "44", "brgy_name": "San Roque"},
    {"brgy_id": "954", "town_id": "44", "brgy_name": "Santo Niño"},
    {"brgy_id": "955", "town_id": "44", "brgy_name": "Sikatuna"},
    {"brgy_id": "956", "town_id": "44", "brgy_name": "Suba"},
    {"brgy_id": "957", "town_id": "44", "brgy_name": "Tanghaligue"},
    {"brgy_id": "958", "town_id": "44", "brgy_name": "San Agustin"},
    {"brgy_id": "959", "town_id": "44", "brgy_name": "Sag"},
    {"brgy_id": "960", "town_id": "44", "brgy_name": "Rizal"},
    {"brgy_id": "961", "town_id": "44", "brgy_name": "Balintawak"},
    {"brgy_id": "962", "town_id": "44", "brgy_name": "Burgos"},
    {"brgy_id": "963", "town_id": "44", "brgy_name": "Busalian"},
    {"brgy_id": "964", "town_id": "44", "brgy_name": "Calituban"},
    {"brgy_id": "965", "town_id": "44", "brgy_name": "Cataban"},
    {"brgy_id": "966", "town_id": "44", "brgy_name": "Guindacpan"},
    {"brgy_id": "967", "town_id": "44", "brgy_name": "Magsaysay"},
    {"brgy_id": "968", "town_id": "44", "brgy_name": "Mahanay"},
    {"brgy_id": "969", "town_id": "44", "brgy_name": "Nocnocan"},
    {"brgy_id": "970", "town_id": "44", "brgy_name": "Poblacion"},
    {"brgy_id": "971", "town_id": "44", "brgy_name": "Zamora"},
    {"brgy_id": "972", "town_id": "46", "brgy_name": "Banlasan"},
    {"brgy_id": "973", "town_id": "46", "brgy_name": "Mahagbu"},
    {"brgy_id": "974", "town_id": "46", "brgy_name": "Manuel A. Roxas"},
    {"brgy_id": "975", "town_id": "46", "brgy_name": "Poblacion"},
    {"brgy_id": "976", "town_id": "46", "brgy_name": "San Isidro"},
    {"brgy_id": "977", "town_id": "46", "brgy_name": "San Vicente"},
    {"brgy_id": "978", "town_id": "46", "brgy_name": "Santo Tomas"},
    {"brgy_id": "979", "town_id": "46", "brgy_name": "Soom"},
    {"brgy_id": "980", "town_id": "46", "brgy_name": "Tagum Norte"},
    {"brgy_id": "981", "town_id": "46", "brgy_name": "Mabuhay Cabigohan"},
    {"brgy_id": "982", "town_id": "46", "brgy_name": "La Victoria"},
    {"brgy_id": "983", "town_id": "46", "brgy_name": "Bongbong"},
    {"brgy_id": "984", "town_id": "46", "brgy_name": "Catoogan"},
    {"brgy_id": "985", "town_id": "46", "brgy_name": "Guinobatan"},
    {"brgy_id": "986", "town_id": "46", "brgy_name": "Hinlayagan Ilaud"},
    {"brgy_id": "987", "town_id": "46", "brgy_name": "Hinlayagan Ilaya"},
    {"brgy_id": "988", "town_id": "46", "brgy_name": "Kauswagan"},
    {"brgy_id": "989", "town_id": "46", "brgy_name": "Kinan-oan"},
    {"brgy_id": "990", "town_id": "46", "brgy_name": "La Union"},
    {"brgy_id": "991", "town_id": "46", "brgy_name": "Tagum Sur"},
    {"brgy_id": "992", "town_id": "47", "brgy_name": "Bagongbanwa"},
    {"brgy_id": "993", "town_id": "47", "brgy_name": "Mocaboc Island"},
    {"brgy_id": "994", "town_id": "47", "brgy_name": "Panadtaran"},
    {"brgy_id": "995", "town_id": "47", "brgy_name": "Panaytayon"},
    {"brgy_id": "996", "town_id": "47", "brgy_name": "Pandan"},
    {"brgy_id": "997", "town_id": "47", "brgy_name": "Pangapasan"},
    {"brgy_id": "998", "town_id": "47", "brgy_name": "Pinayagan Norte"},
    {"brgy_id": "999", "town_id": "47", "brgy_name": "Pinayagan Sur"},
    {"brgy_id": "1000", "town_id": "47", "brgy_name": "Pooc Occidental"},
    {"brgy_id": "1001", "town_id": "47", "brgy_name": "Pooc Oriental"},
    {"brgy_id": "1002", "town_id": "47", "brgy_name": "Potohan"},
    {"brgy_id": "1003", "town_id": "47", "brgy_name": "Talenceras"},
    {"brgy_id": "1004", "town_id": "47", "brgy_name": "Tan-awan"},
    {"brgy_id": "1005", "town_id": "47", "brgy_name": "Ubojan"},
    {"brgy_id": "1006", "town_id": "47", "brgy_name": "Ubay Island"},
    {"brgy_id": "1007", "town_id": "47", "brgy_name": "Tinangnan"},
    {"brgy_id": "1008", "town_id": "47", "brgy_name": "Matabao"},
    {"brgy_id": "1009", "town_id": "47", "brgy_name": "Macaas"},
    {"brgy_id": "1010", "town_id": "47", "brgy_name": "Banlasan"},
    {"brgy_id": "1011", "town_id": "47", "brgy_name": "Batasan"},
    {"brgy_id": "1012", "town_id": "47", "brgy_name": "Bilangbilangan"},
    {"brgy_id": "1013", "town_id": "47", "brgy_name": "Bosongon"},
    {"brgy_id": "1014", "town_id": "47", "brgy_name": "Buenos Aires"},
    {"brgy_id": "1015", "town_id": "47", "brgy_name": "Bunacan"},
    {"brgy_id": "1016", "town_id": "47", "brgy_name": "Cabulihan"},
    {"brgy_id": "1017", "town_id": "47", "brgy_name": "Cahayag"},
    {"brgy_id": "1018", "town_id": "47", "brgy_name": "Cawayanan"},
    {"brgy_id": "1019", "town_id": "47", "brgy_name": "Centro"},
    {"brgy_id": "1020", "town_id": "47", "brgy_name": "Genonocan"},
    {"brgy_id": "1021", "town_id": "47", "brgy_name": "Guiwanon"},
    {"brgy_id": "1022", "town_id": "47", "brgy_name": "Ilihan Norte"},
    {"brgy_id": "1023", "town_id": "47", "brgy_name": "Ilihan Sur"},
    {"brgy_id": "1024", "town_id": "47", "brgy_name": "Libertad"},
    {"brgy_id": "1025", "town_id": "47", "brgy_name": "Villanueva"},
    {"brgy_id": "1026", "town_id": "48", "brgy_name": "Sinandigan"},
    {"brgy_id": "1027", "town_id": "48", "brgy_name": "San Isidro"},
    {"brgy_id": "1028", "town_id": "48", "brgy_name": "San Pascual"},
    {"brgy_id": "1029", "town_id": "48", "brgy_name": "Poblacion"},
    {"brgy_id": "1030", "town_id": "48", "brgy_name": "Pangpang"},
    {"brgy_id": "1031", "town_id": "48", "brgy_name": "Pag-asa"},
    {"brgy_id": "1032", "town_id": "48", "brgy_name": "Los Angeles"},
    {"brgy_id": "1033", "town_id": "48", "brgy_name": "Lomangog"},
    {"brgy_id": "1034", "town_id": "48", "brgy_name": "Katarungan"},
    {"brgy_id": "1035", "town_id": "48", "brgy_name": "Juagdan"},
    {"brgy_id": "1036", "town_id": "48", "brgy_name": "San Vicente"},
    {"brgy_id": "1037", "town_id": "48", "brgy_name": "Sentinela"},
    {"brgy_id": "1038", "town_id": "48", "brgy_name": "Tapal"},
    {"brgy_id": "1039", "town_id": "48", "brgy_name": "Tapon"},
    {"brgy_id": "1040", "town_id": "48", "brgy_name": "Tintinan"},
    {"brgy_id": "1041", "town_id": "48", "brgy_name": "Villa Teresita"},
    {"brgy_id": "1042", "town_id": "48", "brgy_name": "Tubog"},
    {"brgy_id": "1043", "town_id": "48", "brgy_name": "San Francisco"},
    {"brgy_id": "1044", "town_id": "48", "brgy_name": "Tuboran"},
    {"brgy_id": "1045", "town_id": "48", "brgy_name": "Union"},
    {"brgy_id": "1046", "town_id": "48", "brgy_name": "Tipolo"},
    {"brgy_id": "1047", "town_id": "48", "brgy_name": "Imelda"},
    {"brgy_id": "1048", "town_id": "48", "brgy_name": "Ilihan"},
    {"brgy_id": "1049", "town_id": "48", "brgy_name": "Calanggaman"},
    {"brgy_id": "1050", "town_id": "48", "brgy_name": "Cagting"},
    {"brgy_id": "1051", "town_id": "48", "brgy_name": "Bulilis"},
    {"brgy_id": "1052", "town_id": "48", "brgy_name": "Buenavista"},
    {"brgy_id": "1053", "town_id": "48", "brgy_name": "Bood"},
    {"brgy_id": "1054", "town_id": "48", "brgy_name": "Bongbong"},
    {"brgy_id": "1055", "town_id": "48", "brgy_name": "Biabas"},
    {"brgy_id": "1056", "town_id": "48", "brgy_name": "Benliw"},
    {"brgy_id": "1057", "town_id": "48", "brgy_name": "Bay-ang"},
    {"brgy_id": "1058", "town_id": "48", "brgy_name": "California"},
    {"brgy_id": "1059", "town_id": "48", "brgy_name": "Camali-an"},
    {"brgy_id": "1060", "town_id": "48", "brgy_name": "Humayhumay"},
    {"brgy_id": "1061", "town_id": "48", "brgy_name": "Hambabauran"},
    {"brgy_id": "1062", "town_id": "48", "brgy_name": "Guintabo-an"},
    {"brgy_id": "1063", "town_id": "48", "brgy_name": "Governor Boyles"},
    {"brgy_id": "1064", "town_id": "48", "brgy_name": "Gabi"},
    {"brgy_id": "1065", "town_id": "48", "brgy_name": "Fatima"},
    {"brgy_id": "1066", "town_id": "48", "brgy_name": "Cuya"},
    {"brgy_id": "1067", "town_id": "48", "brgy_name": "Casate"},
    {"brgy_id": "1068", "town_id": "48", "brgy_name": "Camambugan"},
    {"brgy_id": "1069", "town_id": "48", "brgy_name": "Achila"},
    {"brgy_id": "1070", "town_id": "49", "brgy_name": "Genoveva"},
    {"brgy_id": "1071", "town_id": "49", "brgy_name": "Ginopolan"},
    {"brgy_id": "1072", "town_id": "49", "brgy_name": "La Victoria"},
    {"brgy_id": "1073", "town_id": "49", "brgy_name": "Lantang"},
    {"brgy_id": "1074", "town_id": "49", "brgy_name": "Limocon"},
    {"brgy_id": "1075", "town_id": "49", "brgy_name": "Loctob"},
    {"brgy_id": "1076", "town_id": "49", "brgy_name": "Magsaysay"},
    {"brgy_id": "1077", "town_id": "49", "brgy_name": "Marawis"},
    {"brgy_id": "1078", "town_id": "49", "brgy_name": "Nailo"},
    {"brgy_id": "1079", "town_id": "49", "brgy_name": "Maubo"},
    {"brgy_id": "1080", "town_id": "49", "brgy_name": "Simang"},
    {"brgy_id": "1081", "town_id": "49", "brgy_name": "Pangi-an"},
    {"brgy_id": "1082", "town_id": "49", "brgy_name": "Omjon"},
    {"brgy_id": "1083", "town_id": "49", "brgy_name": "Danao"},
    {"brgy_id": "1084", "town_id": "49", "brgy_name": "Cutcutan"},
    {"brgy_id": "1085", "town_id": "49", "brgy_name": "Catug-a"},
    {"brgy_id": "1086", "town_id": "49", "brgy_name": "Adlawan"},
    {"brgy_id": "1087", "town_id": "49", "brgy_name": "Anas"},
    {"brgy_id": "1088", "town_id": "49", "brgy_name": "Anonang"},
    {"brgy_id": "1089", "town_id": "49", "brgy_name": "Anoyon"},
    {"brgy_id": "1090", "town_id": "49", "brgy_name": "Balingasao"},
    {"brgy_id": "1091", "town_id": "49", "brgy_name": "Banderahan"},
    {"brgy_id": "1092", "town_id": "49", "brgy_name": "Botong"},
    {"brgy_id": "1093", "town_id": "49", "brgy_name": "Buyog"},
    {"brgy_id": "1094", "town_id": "49", "brgy_name": "Canduao Occidental"},
    {"brgy_id": "1095", "town_id": "49", "brgy_name": "Canduao Oriental"},
    {"brgy_id": "1096", "town_id": "49", "brgy_name": "Canlusong"},
    {"brgy_id": "1097", "town_id": "49", "brgy_name": "Poblacion Oriental"},
    {"brgy_id": "1098", "town_id": "49", "brgy_name": "Cansibao"},
    {"brgy_id": "1099", "town_id": "49", "brgy_name": "Taug"},
    {"brgy_id": "1100", "town_id": "49", "brgy_name": "Tausi-on"},
    {"brgy_id": "1101", "town_id": "49", "brgy_name": "Ticum"},
    {"brgy_id": "1102", "town_id": "43", "brgy_name": "Bool"},
    {"brgy_id": "1103", "town_id": "43", "brgy_name": "Booy"},
    {"brgy_id": "1104", "town_id": "43", "brgy_name": "Cabawan"},
    {"brgy_id": "1105", "town_id": "43", "brgy_name": "Cogon"},
    {"brgy_id": "1106", "town_id": "43", "brgy_name": "Dampas"},
    {"brgy_id": "1107", "town_id": "43", "brgy_name": "Dao"},
    {"brgy_id": "1108", "town_id": "43", "brgy_name": "Manga"},
    {"brgy_id": "1109", "town_id": "43", "brgy_name": "Mansasa"},
    {"brgy_id": "1110", "town_id": "43", "brgy_name": "Poblacion I"},
    {"brgy_id": "1111", "town_id": "43", "brgy_name": "Poblacion II"},
    {"brgy_id": "1112", "town_id": "43", "brgy_name": "Poblacion III"},
    {"brgy_id": "1113", "town_id": "43", "brgy_name": "San Isidro"},
    {"brgy_id": "1114", "town_id": "43", "brgy_name": "Taloto"},
    {"brgy_id": "1115", "town_id": "43", "brgy_name": "Tiptip"},
    {"brgy_id": "1116", "town_id": "43", "brgy_name": "Ubujan"}
  ];
  //barangay list//
}
